[IG]
ig = fsh-generated/resources/ImplementationGuide-de.gematik.fhir.directory.json
# template = fhir.base.template#current
# @spilikin: ich probiere mal das aus. Das wird auch von us core verwendet (https://github.com/HL7/US-Core)
template = hl7.fhir.template#current
