id: de.gematik.fhir.directory
canonical: https://gematik.de/fhir/directory
name: gematik Directory
# FSHOnly: true
title: gematik Directory
status: draft # draft | active | retired | unknown
publisher:
  name: gematik GmbH
  url: https://www.gematik.de/
  # email: test@example.org
copyright: >-
  Copyright gematik GmbH, Berlin, Germany
description: >-
  The gematik Directory Implementation Guide is based on FHIR Version R4 and defines the minimum conformance requirements for accessing the FHIR-Directory.
license: CC0-1.0
date: 2022-05-09
version: 0.8.0-wip
copyrightyear: '2022+'
releaselabel: Release 0.8.0-wip

fhirVersion: 4.0.1

dependencies:
  de.basisprofil.r4: 
    version: 1.3.2
    uri: 'https://simplifier.net/guide/basisprofil-de-r4?version=current'

menu:
  Home: index.html
  Artifacts: artifacts.html