ValueSet: HealthCareServiceTechnicalCharacteristicVS
Id: healthcareservice-technical-characteristic-vs
Title: "HealthCareServiceTechnicalCharacteristicVS"
Description: "HealthCareServiceTechnicalCharacteristicVS"
* insert Meta
* include codes from system VZDHealthCareServiceCharacteristicsCS