Alias: $PatientBezogenenGesundheitsversorgung = http://ihe-d.de/CodeSystems/PatientBezogenenGesundheitsversorgung

ValueSet: IHEXDShealthcareFacilityTypeCodePatientRelatedHealthcare
Id: IHEXDShealthcareFacilityTypeCodePatientRelatedHealthcare
Title: "IHE XDS healthcareFacilityTypeCode Patient Related Healthcare"
Description: """**healthcareFacilityTypeCode (XDSDocumentEntry)**
 This code for an XDS Document represents the type of organizational setting of the clinical encounter during which the documented act occurred."""
* insert Meta
* ^publisher = "IHE Deutschland e.V."
* ^experimental = false
* ^url = "http://ihe-d.de/ValueSets/IHEXDShealthcareFacilityTypeCodePatientRelatedHealthcare"
* $PatientBezogenenGesundheitsversorgung#APD "Ambulanter Pflegedienst"
* $PatientBezogenenGesundheitsversorgung#APD ^extension.url = "http://hl7.org/fhir/StructureDefinition/valueset-concept-comments"
* $PatientBezogenenGesundheitsversorgung#APD ^extension.valueString = "Sozialstationen und gewerblich betriebene ambulante Pflegedienste, die Patienten in der eigenen häuslichen Umgebung betreuen, aber keine ärztlichen Tätigkeiten durchführen."
* $PatientBezogenenGesundheitsversorgung#APO "Apotheke"
* $PatientBezogenenGesundheitsversorgung#APO ^extension.url = "http://hl7.org/fhir/StructureDefinition/valueset-concept-comments"
* $PatientBezogenenGesundheitsversorgung#APO ^extension.valueString = "Eine Einrichtung zur Abgabe und ggf. Lagerung oder Herstellung von Arzneimitteln. Dieser Wert sollte nicht zur Kennzeichnung von Daten aus Krankenhausapotheken verwendet werden."
* $PatientBezogenenGesundheitsversorgung#BER "Ärztlicher Bereitschaftsdienst"
* $PatientBezogenenGesundheitsversorgung#BER ^extension.url = "http://hl7.org/fhir/StructureDefinition/valueset-concept-comments"
* $PatientBezogenenGesundheitsversorgung#BER ^extension.valueString = "Der ärztliche Bereitschaftsdienst wird auch als Kassenärztlicher Notdienst bezeichnet. Er wird häufig durch Niedergelassene Ärzte durchgeführt und von der Kassenärztlichen Vereinigungen organisiert, da diese die Verantwortung für die Sicherstellung der medizinischen Versorgung auch außerhalb der üblichen Öffnungszeiten hat. Der Dienst ist vom\n                        Rettungsdienst zu unterscheiden, der auf speziell ausgebildete Notärzte zurückgreift."
* $PatientBezogenenGesundheitsversorgung#PRA "Arztpraxis"
* $PatientBezogenenGesundheitsversorgung#PRA ^extension.url = "http://hl7.org/fhir/StructureDefinition/valueset-concept-comments"
* $PatientBezogenenGesundheitsversorgung#PRA ^extension.valueString = "Arbeitsplatz einer oder mehrerer niedergelassenen Ärztinnen oder Zahnärztinnen. Umfasst sowohl den klassischen \"Einzelsitz\", wie auch die Gemeinschaftspraxis oder die Praxisgemeinschaft. Auch mobile Arztpraxen, die ambulante Zentrumsdialyse (https://www.gbe-bund.de/glossar/Dialyseversorgungsarten.html) und Zahnarztpraxen werden durch diesen Wert\n                        abgedeckt. Ebenso werden niedergelassene Laborarztpraxen und von ärztlichen Psychotherapeuten geführte Arztpraxen über diesen Wert abgedeckt. Arztpraxen die Teil eines MVZ sind werden über das Konzept MVZ (\"Medizinisches Versorgungszentrum\")\n                        abgebildet."
* $PatientBezogenenGesundheitsversorgung#BAA "Betriebsärztliche Abteilung"
* $PatientBezogenenGesundheitsversorgung#BAA ^extension.url = "http://hl7.org/fhir/StructureDefinition/valueset-concept-comments"
* $PatientBezogenenGesundheitsversorgung#BAA ^extension.valueString = "Betriebsärztliche Abteilung in einer nicht-medizinischen Organisation (z.B. große Firmen die selbst Ärzte anstellen) die eine medizinische Betreuung für Mitarbeiter anbietet. Betriebsärztliche Tätigkeiten einer Ärztin mit eigener Praxis oder eines Diensts eines Krankenhauses fallen nicht unter dieses Konzept, sondern werden mit dem Konzept PRA\n                        (\"Arztpraxis\"), bzw. KHS (\"Krankenhaus\") abgebildet."
* $PatientBezogenenGesundheitsversorgung#BHR "Gesundheitsbehörde"
* $PatientBezogenenGesundheitsversorgung#BHR ^extension.url = "http://hl7.org/fhir/StructureDefinition/valueset-concept-comments"
* $PatientBezogenenGesundheitsversorgung#BHR ^extension.valueString = "Staatliche oder kommunale Gesundheitsbehörde."
* $PatientBezogenenGesundheitsversorgung#HEB "Hebamme/Geburtshaus"
* $PatientBezogenenGesundheitsversorgung#HEB ^extension.url = "http://hl7.org/fhir/StructureDefinition/valueset-concept-comments"
* $PatientBezogenenGesundheitsversorgung#HEB ^extension.valueString = "Eine freiberuflich tätige Hebamme; bzw. eine in Kooperation mit anderen Hebammen tätige Hebamme. Dieser Wert deckt auch Geburtshäuser ab, d.h. üblicherweise von Hebammen betriebene außerklinische Einrichtungen."
* $PatientBezogenenGesundheitsversorgung#HOS "Hospiz"
* $PatientBezogenenGesundheitsversorgung#HOS ^extension.url = "http://hl7.org/fhir/StructureDefinition/valueset-concept-comments"
* $PatientBezogenenGesundheitsversorgung#HOS ^extension.valueString = "Eine stationäre oder ambulante Einrichtung der Sterbebegleitung. Dies umfasst sowohl Pflegeheim-ähnliche Einrichtungen, wie auch Einrichtungen die den Patienten in der eigenen häuslichen Umgebung betreuen. Sowohl Einrichtungen unter ärztlicher Leitung, wie auch unter pflegerischer Leitung werden hier zusammengefasst."
* $PatientBezogenenGesundheitsversorgung#KHS "Krankenhaus"
* $PatientBezogenenGesundheitsversorgung#KHS ^extension.url = "http://hl7.org/fhir/StructureDefinition/valueset-concept-comments"
* $PatientBezogenenGesundheitsversorgung#KHS ^extension.valueString = "Eine Einrichtung die als Krankenhaus nach dem Krankenhausfinanzierungsgesetz (KHG) zu verstehen ist, mit Ausnahme von Reha-Kliniken. Zu den Krankenhäusern gehören hierbei auch Zahnkliniken. Zusätzlich fallen unter diesen Wert auch Krankenhäuser auf die das KHG keine Anwendung findet (siehe §3, z.B. im Straf- oder Maßregelvollzug, Polizeikrankenhäuser,\n                        Bundeswehrkrankenhäuser...), solange es sich nicht um Einrichtungen der medizinischen Rehabilitation handelt.  Für Dokumente aus der Abteilung Krankenhausapotheke oder aus Krankenhausambulanzen sollte immer das Konzept KHS \"Krankenhaus\" verwendet werden. Auch bei vornehmlich telemedizinisch erbrachten Leistungen eines Krankenhauses (z.B. Teleradiologie)\n                        sollte das Konzept KHS \"Krankenhaus\"\" verwendet werden.  Für angeschlossene, aber selbständige Einrichtungen, wie z.B. ein zum Krankenhaus gehöriges MVZ oder Hospiz, sollte dieses Konzept (KHS \"Krankenhaus\"), sondern ein spezifischeres Konzept für den Einrichtungstyp verwendet werden. Dazu zählen auch ausgegründete Labore, die als Arztpraxis abgebildet\n                        werden, da sie eine entsprechende KV-Zulassung benötigen.  Psychotherapeutische, psychiatrische und psychosomatische Abteilungen von Krankenhäusern und eigenständige Fachkliniken aus diesem Bereich werden auch mit diesem Wert abgedeckt, unabhängig davon ob die Dienste stationär, als Tagesklinik oder ambulant angeboten werden."
* $PatientBezogenenGesundheitsversorgung#MVZ "Medizinisches Versorgungszentrum"
* $PatientBezogenenGesundheitsversorgung#MVZ ^extension.url = "http://hl7.org/fhir/StructureDefinition/valueset-concept-comments"
* $PatientBezogenenGesundheitsversorgung#MVZ ^extension.valueString = "Einrichtung zur ambulanten medizinischen Versorgung nach §95 SGB V; dieses Konzept sollte für ein MVZ unabhängig von der Besitzerstruktur gewählt werden, d.h. auch MVZ die einem Krankenhaus gehören, sollten als MVZ gekennzeichnet werden."
* $PatientBezogenenGesundheitsversorgung#HAN "Medizinisch-technisches Handwerk"
* $PatientBezogenenGesundheitsversorgung#HAN ^extension.url = "http://hl7.org/fhir/StructureDefinition/valueset-concept-comments"
* $PatientBezogenenGesundheitsversorgung#HAN ^extension.valueString = "Eine Einrichtung des medizinisch-technischen Handwerks, wie Augenoptiker, Hörakustiker-Fachgeschäft, Diätkoch, Orthopädische Schuhmacher, sowie Orthopädische Fachgeschäfte und Sanitätshäuser."
* $PatientBezogenenGesundheitsversorgung#REH "Medizinische Rehabilitation"
* $PatientBezogenenGesundheitsversorgung#REH ^extension.url = "http://hl7.org/fhir/StructureDefinition/valueset-concept-comments"
* $PatientBezogenenGesundheitsversorgung#REH ^extension.valueString = "Eine ambulante, teilstationäre oder stationäre Einrichtung der medizinischen Rehabilitation unter ärztlicher Leitung. Darunter fallen sowohl Kur-Einrichtungen und Reha-Kliniken als auch dezentrale Organisationsformen aus dem ambulanten Sektor."
* $PatientBezogenenGesundheitsversorgung#HEI "Nicht-ärztliche Heilberufs-Praxis"
* $PatientBezogenenGesundheitsversorgung#HEI ^extension.url = "http://hl7.org/fhir/StructureDefinition/valueset-concept-comments"
* $PatientBezogenenGesundheitsversorgung#HEI ^extension.valueString = "Von nicht-ärztlichen Heilberuflern betriebene Einrichtungen zur Beratung, Therapie oder Betreuung. Darunter fallen Praxen von Heilpraktikerinnen, Physiotherapeutinnen, Ergotherapeutinnen, Podologinnen, Masseurinnen, Logopädinnen, Sprachtherapeutinnen, Diätassistentinnen, sowie human-medizinische Beratungsstellen. Auch nicht-ärztliche psychotherapeutische\n                        Praxen, z.B. von Diplom oder Master-Psychologen, gehören dazu.  Dokumente von freiberuflichen Hebammen fallen nicht in diese Gruppe, sondern sind mit dem Konzept für HEB \"Hebamme/Geburtshaus\" zu kennzeichnen.  Dokumente von Pflegediensten oder freiberuflichen Pflegekräften fallen nicht in diese Gruppe sondern sind mit dem Konzept APD\n                         \"Ambulante Pflegedienste\" zu kennzeichnen."
* $PatientBezogenenGesundheitsversorgung#PFL "Pflegeheim"
* $PatientBezogenenGesundheitsversorgung#PFL ^extension.url = "http://hl7.org/fhir/StructureDefinition/valueset-concept-comments"
* $PatientBezogenenGesundheitsversorgung#PFL ^extension.valueString = "Eine Einrichtung zur Unterbringung und Versorgung pflegebedürftiger Menschen. Umfasst Altenpflegeheime und Pflegeheime für Menschen mit Behinderung. Die Einrichtungen versorgen Menschen üblicherweise langfristig, aber auch Kurzzeitpflege der genannten Personengruppen ist durch dieses Konzept abgedeckt."
* $PatientBezogenenGesundheitsversorgung#RTN "Rettungsdienst"
* $PatientBezogenenGesundheitsversorgung#RTN ^extension.url = "http://hl7.org/fhir/StructureDefinition/valueset-concept-comments"
* $PatientBezogenenGesundheitsversorgung#RTN ^extension.valueString = "Einrichtungen des zivilen Rettungsdienst, wie z.B. Rettungswachen, Wasserrettung, etc."
* $PatientBezogenenGesundheitsversorgung#SEL "Selbsthilfe"
* $PatientBezogenenGesundheitsversorgung#SEL ^extension.url = "http://hl7.org/fhir/StructureDefinition/valueset-concept-comments"
* $PatientBezogenenGesundheitsversorgung#SEL ^extension.valueString = "Einrichtungen zur Information und Beratung zur Selbsthilfe sowie Selbsthilfegruppen, z.B. Suchtberatung, AIDS-Hilfe, etc."
* $PatientBezogenenGesundheitsversorgung#TMZ "Telemedizinisches Zentrum"
* $PatientBezogenenGesundheitsversorgung#TMZ ^extension.url = "http://hl7.org/fhir/StructureDefinition/valueset-concept-comments"
* $PatientBezogenenGesundheitsversorgung#TMZ ^extension.valueString = "Eine dedizierte Einrichtung die ausschließlich auf die telemedizinische Betreuung von Patienten abzielt. Dies umfasst sowohl dedizierte Care Management Organisationen, wie auch Telemonitoring-Zentren. Dokumente die im Rahmen von telemedizinischen Dienstleistungen von Krankenhäusern oder niedergelassenen Ärzten erbracht werden, sollten nicht mit diesem\n                        Konzept gekennzeichnet werden, sondern mit dem Konzept für KHS \"Krankenhaus\" bzw. PRA \"Arztpraxis\"."