= Verzeichnisdienst der Telematikinfrastruktur
gematik, Systems Engineering
:source-highlighter: rouge
:title-page:
:imagesdir: images/
//:sectnums:
//:toc:
//:toclevels: 3
//:toc-title: Inhaltsverzeichnis

ifndef::env-github[]
image::gematik_logo.svg[gematik,float="right"]
endif::[]
ifdef::env-github[]
++++
<img align="right" role="right" src="images/gematik_logo.svg?raw=true"/>
++++
endif::[]

image:https://shields.io/badge/gem Spec VZD-v1.14.0-blue[link="https://fachportal.gematik.de/fachportal-import/files/gemSpec_VZD_V1.14.0.pdf"]
image:https://shields.io/badge/gemILF_Pflege_VZD-v1.5.4-green[link="https://github.com/gematik/api-vzd/blob/gemILF_Pflege_VZD/1.5.4/docs/gemILF_Pflege_VZD.adoc"]
image:https://shields.io/badge/simplifier.net-0.8.0beta6-red[link="https://simplifier.net/vzd-fhir-directory"] +
image:https://shields.io/badge/Admin API-1.9.5-green?logo=swagger[link="https://github.com/gematik/api-vzd/blob/I_Directory_Administration/1.9.5/src/openapi/DirectoryAdministration.yaml"]
image:https://shields.io/badge/KIM API-1.2.4-green?logo=swagger[link="https://github.com/gematik/api-vzd/blob/I_Directory_Administration/1.2.4/src/openapi/DirectoryApplicationMaintenance.yaml"]

== Aktuelles

* *14.12.2022* 📄 https://fachportal.gematik.de/schnelleinstieg/downloadcenter/releases#c6770[Spezifikationen Verzeichnisdienst „VZD FHIR 1.0.0“]
* *26.09.2022* 👨‍💻 https://github.com/gematik/api-vzd/blob/gemILF_Pflege_VZD/1.5.4/docs/gemILF_Pflege_VZD.adoc[Implementierungsleitfaden v1.5.4]
* *23.06.2022* 📄 link:https://github.com/gematik/api-vzd/blob/gemILF_Pflege_VZD/1.5.3/docs/gemILF_Pflege_VZD.adoc[Implementierungsleitfaden v1.5.3]. Ab dieser Version wird das Dokument über github.com veröffentlicht. 
* *31.05.2022* link:CHANGELOG.adoc[Produktrelease v3.1.0-14]
* *8.04.2022* 👨‍💻 https://github.com/gematik/api-vzd/blob/I_Directory_Application_Maintenance/1.1.4/src/openapi/DirectoryApplicationMaintenance.yaml[Directory Application Maintenance API v1.1.4]
* *8.04.2022* 👨‍💻 https://github.com/gematik/api-vzd/blob/I_Directory_Administration/1.8.1/src/openapi/DirectoryAdministration.yaml[Directory Administration API v1.8.1]
* *25.02.2022* 🔥 https://simplifier.net/packages/de.gematik.fhir.directory/0.6.1/~introduction[FHIR Package 0.6.1]
* *17.02.2022* 🎁 link:CHANGELOG.adoc[Produktrelease v3.1.0-11]
* *14.02.2022* 📄 https://fachportal.gematik.de/fileadmin/Fachportal/Downloadcenter/Implementierungsleitfaeden/gemILF_Pflege_VZD_V1.5.2.pdf[Implementierungsleitfaden v1.5.2]

== GitHub Branches
Der Verzeichnisdienst wird auf verschiedenen GitHub Branches dokumentiert:

- *main* Branch: Enthält die Dokumentation passend für die aktuelle Verzeichnisdienst Produktivumgebung (PU)
- *develop* Branch: Enthält die Dokumentation passend für den aktuelle in Entwicklung befindlichen Verzeichnisdienst.
- *feature/** Branches: Diese Branches werden zur Vorbereitung und Diskussion von neuen Themen genutzt, die noch nicht in Entwickung sind. Diese Dokumente können unvollständig sein und sich bis zur Fertigstellung ändern.


== Kontextabgrenzung

.*Verzeichnisdienst Systemkontext*
image::VZD_Systemkontext.svg[VZD Systemkontext]
{zwsp} +
Verzeichnisdienst der TI verwaltet Einträge von Leistungserbringern und Organisationen/Institutionen mit allen definierten Attributen, die in das Verzeichnis aufgenommen werden sollen. Anhand einer Suchanfrage können diese Daten abgefragt werden (z. B. Adressdaten, X.509-Zertifikate). Ferner können Einträge des Verzeichnisses durch Kartenherausgeber (Basisdaten) oder berechtigte fachanwendungsspezifische Dienste (Fachanwendungsdaten) geändert, hinzugefügt und gelöscht (Kartenherausgeber vollständige Einträge, fachanwendungsspezifische Dienste nur die jeweiligen Fachdaten) werden.

Verzeichnisdienst bietet folgende Außenschnittstellen an (s. Nummerierung in der Abbildung):

1. Über den TI-Konnektor wird dem KIM-Client sowie Primärsystemen eine LDAP Schnittstelle zur Abfrage der Daten bereitgestellt. Schnittstelle `I_Directory_Query`, dezentral.
2. Die Konnektoren leiten die Anfragen zustandslos über das zentrale Netz der TI an den Verzeichnisdienst weiter. Über die LDAP Schnittstelle des zentrale betriebenen VZD werden speziell für solche Abfragen aufbereitete und optimierte Daten durchsucht (so genannte flache Liste). Schnittstelle `I_Directory_Query`, zentral.
3. Die Kartenherausgeber (bspw. Landesärztekammer oder Kassenzahnärztliche Vereinigungen) in Kooperation mit Trust Service Provider sind verantwortlich für die Befüllung des VZD mit Basisdaten und Zertifikaten. Hierfür stell VZD eine REST API für die Administration der Daten im Verzeichnisdienst. Schnittstelle `I_Directory_Administration`.
4. Die KIM Anbieter ergänzen die Basisdaten um eigene Inhalte, insb. um die KIM-EMail-Adressen. Schnittstelle `I_Application_Maintenance`.
5. Für die Suche der Apotheken, z.B. in der gematik eRezept APP, existiert ein dediziertes Apothekenverzeichnis (ApoVZD). ApoVZD synchronisiert regelmäßig die Daten aus dem VZD und ergänzt diese um weitere Inhalte (z.B. um Geolokalisierung und Öffnungszeiten der Apotheken). Schnittstelle `I_Directory_Administration`, analog zu p.3.
6. Für die Suche der Leistungserbringer-Institutionen im Rahmen der Berechtigungsvergabe in der elektronischen Patientenakte (ePA),vermittelt das ePA-Aktensystem die Kommunikation zwischen VZD und ePA-Frontend. Schnittstelle `I_Directory_Query`, zentral.
7. _In Entwicklung_: TIM Anbieter registrieren sich und verifizieren sich gegenseitig mit Hilfe von VZD. Schnittstelle. `I_Directory_TIM_Provider_Services`
8. _In Entwicklung_: VZD bietet direkten Zugriff zur den Daten über FHIR REST Schnittstellen für die TIM Clients und perspektivisch anderen registrierten Clients. Schnittstelle `I_Directory_FHIR#search`.
9. _In Entwicklung_: Die Leistungserbringer können ihre Daten selbstständig administrieren, um z.B. die Organisationsstrukturen und Standorte zur erfassen. Schnittstelle `I_Directory_FHIR#owner`.

== Systemarchitektur

Die folgende Abbildung gibt einen Überblick über die Systemarchitektur des Verzeichnisdienstes.

image::VZD_Architektur.svg[VZD overview]

== LDAP-Directory Datenmodell

image::VZD_LDAP_Directory_Datenmodell.svg[Datenmodell]


* link:docs/LDAP_Attribute.adoc[LDAP Attribute]
* link:docs/LDAP_Search.adoc[LDAP Suche-Tips]

== FHIR-Directory Datenmodell

image::VZD_FHIR_Directory_Resourcen.svg[Datenmodell]
