= Suche im Verzeichnisdienst
gematik, Systems Engineering
:source-highlighter: rouge
:title-page:
:imagesdir: images/
//:sectnums:


ifndef::env-github[]
image::gematik_logo.svg[gematik,float="right"]
endif::[]
ifdef::env-github[]
++++

++++
endif::[]


== Allgemeines

Die Seite gibt Hinweise zur Suche im VZD für Anwendungen. Die Suche von Einträgen für den Anwendungen/Endanwender ist über Schnittstelle I_Directory_Query mit LDAPv3 möglich. Gesucht werden kann nach allen Attributen.

=== Eine Auswahl von Suchkriterien:

*Suche nach Art der Organisation/Leistungserbringers und Spezialisierung*

Dafür kann man unter anderem folgende Attribute in der Suchanfrage verwenden:

* [entryType] 
** Eintragstyp - Siehe [gemSpec_VZD#Tab_VZD_Mapping_Eintragstyp_und_ProfessionOID].
  
* [ProfessionOID] 
** Profession OID - Siehe [gemSpec_VZD#Tab_VZD_Mapping_Eintragstyp_und_ProfessionOID].

* [specialization] 
** Fachgebiet entsprechend https://wiki.hl7.de/index.php?title=IG:Value_Sets_f%C3%BCr_XDS#DocumentEntry.practiceSettingCode[FHIR HL7]

*Suche nach Adresse bzw. in einem Suchgebiet*

Dafür kann man unter anderem folgende Attribute in der Suchanfrage verwenden:

* [stateOrProvinceName] 
** Bundesland - z.B. "Berlin"
  
* [postalCode] 
** Postleitzahl - z.B. "10117"

* [localityName] 
** Ort - z.B. "Berlin"

* [streetAddress] 
** Straße - z.B. "Friedrichstraße"

*Suche bei bekanntem Namen*

Dafür kann man unter anderem folgende Attribute in der Suchanfrage verwenden:

* [displayName] 
** Name der Organisation oder der Person - z.B. "Charité"
** Für die Attribute kann ebenfalls die Suche mit Wildcards entsprechend LDAP genutzt werden z.B. "Charité*".

===   Spezielle Attribute
