@startuml

package "Krankenhaus" {
  
class Organization_Krankenhaus {
+identifier : telematikID 5-2-260571421, IKNR 260571421 - Standortdaten_HauptIK
+name :      Katholische Hospitalvereinigung Ostwestfalen gem.GmbH
+name_StVz : Katholische Hospitalvereinigung Ostwestfalen gGmbH Bielefeld
-alias : -
+type : 1.2.276.0.76.4.53 Krankenhaus
+active : true
}



class HealthcareService_Krankenhaus {
+type : "GESU": "Öffentliches Gesundheitswesen"
#speciality : -
-name : -
+availableTime: Öffnungszeiten
}

Organization_Krankenhaus <-- HealthcareService_Krankenhaus : providedBy
HealthcareService_Krankenhaus --> Location_Krankenhaus : location
HealthcareService_Krankenhaus --> Endpoint_Krankenhaus : endpoint


class Location_Krankenhaus {
#name : -
+address : 33615 Bielefeld, Kiskerstraße 26
#address_StVz : Keine Adr., nur TrägerBezeichnung 
#position : -
}


class Endpoint_Krankenhaus {
#name: Name
#endpointVisibility : -
#status : active
#connectionType : EndpointConnectionType
#payloadType : EndpointPlayloadType
#address : KIM/TIM Adresse
}

}

note right of Krankenhaus 
   Daten werden
   nur aus dem VZD
   übernommen.
   Erkennung Zusammengehörigkeit
   über IK.
end note   

package "Standort" {

class Organization_Standort {
+identifier : khId
+name : Marienhospital Oelde
-alias : -
-type : -
-active : "Aktiv" aus Standortdaten
}
note right of Organization_Standort 
   Nur für zusätzliche
   Standorte wird eine
   Unterorganisation angelegt
end note 

Organization_Krankenhaus <-- Organization_Standort : "partOf"
HealthcareService_Krankenhaus -[hidden]right-> Organization_Standort

class HealthcareService_Standort {
-type : -
-speciality : -
-name : -
-telecom : -
-availableTime: -
}

HealthcareService_Standort --> Location_Standort : location
Organization_Standort <-- HealthcareService_Standort : providedBy



class Location_Standort {
-name : -
+address : 59302 Oelde, Westfalen, Spellerstraße 16
+position : GeoKoordinaten
}

}

package "Einrichtung" {

class Organization_Einrichtung {
+identifier : soId 2582
+name : Zentrale Ambulanz Marienhospital
-alias : -
+type : 13 
-active : Aktiv aus Standortdaten
}


Organization_Standort <-- Organization_Einrichtung : "partOf"

class HealthcareService_Einrichtung {
-type : -
-speciality : -
-name : -
-telecom : -
-availableTime: -
}

HealthcareService_Einrichtung --> Location_Einrichtung : location
Organization_Einrichtung <-- HealthcareService_Einrichtung : providedBy



class Location_Einrichtung {
-name : -
+address : 59302 Oelde, Westfalen, Spellerstraße 16
+position : GeoKoordinaten
}

}


package "Fachabteilung" {


class Organization_Fachabteilung {
+identifier : erId aus Standortdaten
-name : -
-alias : -
+type : Fachabteilungsschlüssel aus Standortdaten
-active : -
}


Organization_Einrichtung <-- Organization_Fachabteilung : "partOf"

class HealthcareService_Fachabteilung {
-type : -
-speciality : -
-name : -
-telecom : -
-availableTime: -
}

HealthcareService_Fachabteilung --> Location_Fachabteilung : location
Organization_Fachabteilung <-- HealthcareService_Fachabteilung : providedBy


class Location_Fachabteilung {
-name : -
-address : -
-position : -
}

}

note right of Fachabteilung 
   Link zur 
   Einrichtung 
   unklar
end note  

@enduml
