skinparam DefaultFontName Helvetica
skinparam Shadowing false

skinparam ComponentStyle rectangle
skinparam ComponentBackgroundColor white
skinparam ComponentBorderColor black

skinparam RectangleBackgroundColor white
skinparam RectangleBorderColor black