@startuml
skinparam dpi 100
skinparam WrapWidth 200
skinparam monochrome true

'title "FHIR-Directory, Sequenzdiagram SSP Authenticate mit Passwort"
actor o as "Org-Admin\noder LE"
participant cl as "Browser\nSSP Frontend"
participant be as "SSP Backend"
participant au as "Auth-Service"
participant fp as "FHIR-Proxy"
participant fd as "FHIR-Directory"


o -> cl: [1] Suchanfrage zusammenstellen
activate cl
cl -> be: [2] Suchanfrage & Token
activate be

be -> au: [3] Token Validieren
activate au
au -> au: [4] Token validieren
au -> be: [5] Validierungsergebnis
deactivate au

be -> be: [6] Berechtigungen ermitteln
be -> fp: [7] Suchanfrage & SSP Backend Token
activate fp
fp -> fp: [8] Validiere SSP Backend Token
fp -> fd: [9] Suchanfrage
activate fd

fd -> fp: [10] Suchergebnis
deactivate fd
fp -> be: [10] Suchergebnis
deactivate fp
be -> cl: [10] Suchergebnis
deactivate be

cl -> o: [11] Anzeige Suchergebnis
deactivate cl

@enduml
