@startuml SequenceDiagram.FHIR-Directory.tim_provider_services
skinparam dpi 100
skinparam WrapWidth 200
skinparam monochrome false

autonumber "<b>[00]"

participant rd as "TI-Messenger-Fachdienst\nRegistrierungsdienst"
participant oa as "TI-Provider\nOAuth-Server"
box <size:16>VZD-FHIR-Directory</size> #WhiteSmoke
participant fp as "VZD FHIR TIM-Provider-API"
participant fa as "Auth-Service"
participant hs as "TI-Messenger-Service\nMessenger Proxy"

end box

rd -> oa: POST /token (client_id, client_secret)
activate rd
activate oa
oa -> oa: prüfe client_id und client_secret
oa --> rd: ti-provider-accesstoken
deactivate oa

rd -> fa: GET /ti-provider-authenticate\n(Authorization: "Bearer ti-provider-accesstoken")
activate fa
fa -> fa: prüfe ti-provider-accesstoken
fa --> rd: provider-accesstoken
deactivate fa


alt#LightGrey #MISTYROSE  <size:16>Matrix-Domain nicht in der Föderation enthalten</size>
group optional
rd -> fp: POST /tim-provider-services/federation\n(Authorization: "Bearer provider-accesstoken")\n{domain, telematikID, isInsurance}
activate fp
fp -> hs: GET {domain}/.well-known/matrix/server:443
activate hs
alt#LightGrey #MISTYROSE  <size:16>well-known information not available</size>
hs -> fp: HTTP ERROR 
fp -> fp: Store 443 as default PORT for domain
end

hs -> fp : HTTP 200 OK Response body { "m.server": "HOSTNAME:PORT" }
deactivate hs
fp -> fp : Store PORT for domain


fp --> rd: HTTP 200 OK Response body domainArray json
deactivate fp
end
group optional
rd -> fp: GET /tim-provider-services/FederationList/federationList.jws\n(Authorization: "Bearer provider-accesstoken)
activate fp
fp --> rd: HTTP 200 OK Response body federationList json
deactivate fp
end
group optional
rd -> fp: GET /tim-provider-services/localization?mxid=[MXID in URL Form]\n(Authorization: "Bearer provider-accesstoken)
activate fp
fp --> rd: HTTP 200 OK Response body <enum: [org, pract, orgPract, none]> json
deactivate fp
end

@enduml
