@startuml
skinparam dpi 100
skinparam WrapWidth 200
skinparam monochrome true

'title "FHIR-Directory, Sequenzdiagram SSP Datenänderung"
actor o as "Org-Admin\noder LE"
participant cl as "Browser\nSSP Frontend"
participant be as "SSP Backend"
participant fp as "FHIR-Proxy"
participant fd as "FHIR-Directory"


o -> cl: [1] VZD-Eintrag aktualisieren
activate cl
cl -> be: [2] Aktualisierter VZD-Eintrag & Token
activate be

be -> be: [3] Token Validieren & Berechtigungen ermitteln
be -> fd: [4] Aktualisierter VZD-Eintrag & Token

activate fd
fd -> fp: [5] Ergebnis der Datenänderung
deactivate fd
fp -> be: [5] Ergebnis der Datenänderung
deactivate fp
be -> cl: [5] Ergebnis der Datenänderung
deactivate be

cl -> o: [6] Anzeige Ergebnis der Datenänderung
deactivate cl

@enduml
