@startuml
skinparam dpi 100
skinparam WrapWidth 200
skinparam monochrome true

'title "FHIR-Directory, Sequenzdiagram SSP Authenticate mit Passwort"
actor o as "Org-Admin\noder LE"
participant cl as "Browser\nSSP Frontend"
participant be as "SSP Backend"
participant fd as "FHIR-Directory"


o -> cl: [1] Suchanfrage zusammenstellen
activate cl
cl -> be: [2] Suchanfrage & Token
activate be



be -> be: [3] Berechtigungen ermitteln
be -> fd: [4] Suchanfrage & Token
activate fd

fd -> be: [5] Suchergebnis
deactivate fd

be -> cl: [6] Suchergebnis
deactivate be

cl -> o: [7] Anzeige Suchergebnis
deactivate cl

@enduml
