= FHIR VZD HOWTO UseCases
:source-highlighter: rouge
:icons:
:title-page:
:imagesdir: /images/
ifdef::env-github[]
:toc: preamble
endif::[]
ifndef::env-github[]
:toc: left
endif::[]
:toclevels: 3
:toc-title: Table of Contents
:sectnums:


image::gematik_logo.svg[gematik,float="right"]

[width="100%",cols="50%,50%",options="header",]
|===
|Version: |0.0.1
|Referencing: |gemILF_FHIR_VZD
|===

[big]*Document history*

[width="100%",cols="11%,11%,7%,58%,13%",options="header",]
|===
|*Version* +
 |*Stand* +
 |*Chap./ Page* +
 |*Change reason, special instructions* +
 |*Editing* +

|0.0.1 |26.03.25 | |Initial document |gematik

|===

== Classification of the document
=== Objective
This document sums up examples in interacting with the FHIR VZD. 

=== Target group

The document is aimed at software developers who are involved in implementing a client that interacts with the APIs of the VZD-FHIR-Directory.

=== Scope

*Intellectual property/patent notice*

_The following specification was created by gematik solely from a technical point of view. In individual cases, it cannot be ruled out that the implementation of the specification will interfere with the technical property rights of third parties. It is solely up to the supplier or manufacturer to take suitable measures to ensure that the products and/or services offered by him on the basis of the specification do not infringe third-party property rights and, if necessary, to obtain the necessary permits/licenses from the property right holders concerned. In this respect, gematik GmbH assumes no liability whatsoever._


== Administration of value-added data by the owner of the FHIR VZD Entry
The VZD Entries are administrated by the responsible healthcare organizations. Some value-added data can be administrated by the owner of the FHIR VZD Entry.
The link:FHIR_VZD_HOWTO_Data.adoc#directory-of-organizations[FHIR VZD data model] describes which data the owner can maintain himself (column "Changable by owner" in the tables). +
This section describes how to implement the administration of value-added data in the client (e.g. PVS/AVS/...).

=== Authentication
The value-added data is administrated via the FHIR VZD /owner interface.
To access the /owner API a valid provider access_token is needed that can be obtained by authenticating via the following via one of the following options

- link:FHIR_VZD_HOWTO_Authenticate.adoc#24-authenticate-for-the-owner-endpoint-as-an-user[Authenticate for the /owner interface by using a smartcard (HBA/SMC-B)]. This has to be the smartcard with the telematikID of the FHIR VZD Entry which is changed. An option is, to link:FHIR_VZD_HOWTO_Authenticate.adoc#25-authenticate-using-the-gematik-authenticator[use the gematik Authenticator]  simplify the interaction with a connector, the card terminals and the users smartcards.

- If the FHIR VZD Organization Entry owns a TIM domain, then the  link:FHIR_VZD_HOWTO_Authenticate.adoc#23-authenticate-for-the-owner-endpoint-as-an-organization[Authenticate for the /owner interface as an organization] authentication can be used.

[NOTE]
====
You can find sample code for the authentication here link:https://github.com/gematik/api-vzd/tree/main/samples/directory-samples-java/auth-samples[Java sample] 
and here link:https://github.com/gematik/api-vzd/tree/main/samples/directory-samples-python/directory_samples[Python sample]
====

=== Administration of value-added data
==== Search
First you have to find the resource instance. Use the operations, described in the link:FHIR_VZD_HOWTO_Search.adoc[FHIR VZD HOWTO Search]. +
In the search result the resource data is contained.

==== Change data
Which attributes of which resources can be added or modified is described in the link:FHIR_VZD_HOWTO_Data.adoc[FHIR VZD data model]. +
The simplifier profile of the FHIR VZD can be found here link:https://simplifier.net/vzd-fhir-directory[gematik FHIR Directory].

[IMPORTANT]
====
The client has to ensure, that the telematikID of the resource instance (or its superior Organization/Practitioner resource) and the token (see step "Authentication) match. The FHIR VZD will deny all write operations for resources with other telematikIDs. +
====

A pharmacy/organization may have several HealtcareServices.

====
++++
<p align="center">
  <img width="55%" src=../images/diagrams/ClassDiagram.Org.with.several.HCS.svg>
</p>
++++
====
The "main" HealtcareServices is marked with code "ldap" in HealthcareService.meta.tag:Origin
====
                    "tag": [
                        {
                            "system": "https://gematik.de/fhir/directory/CodeSystem/Origin",
                            "code": "ldap",
                            "display": "Synchronized from LDAP VZD",
                            "userSelected": false
                        }
                    ]
====
This HealtcareServices - marked with "ldap" - has to be updated with value-added data. 



===== Data categories

*Type and Services of the pharmacy* +
 +
The type and the services of a pharmacy can be administrated.

Used FHIR VZD attributes: +

* HealthcareService.type - See simplifier profile for possible values.

.Example data:
[%collapsible%open]
====
[source,txt, linenums]
----
                "type": [
                    {
                        "coding": [
                            {
                                "system": "https://gematik.de/fhir/directory/CodeSystem/PharmacyTypeCS",
                                "code": "offizin-apotheke",
                                "display": "Offizin-Apotheke"
                            },
                            {
                                "system": "https://gematik.de/fhir/directory/CodeSystem/PharmacyTypeCS",
                                "code": "versandapotheke",
                                "display": "Versandapotheke"
                            }
                        ],
                        "text": "apo-vzd"
                    },
                    {
                        "coding": [
                            {
                                "system": "https://gematik.de/fhir/directory/CodeSystem/PharmacyTypeCS",
                                "code": "offizin-apotheke",
                                "display": "Offizin-Apotheke"
                            }
                        ],
                        "text": "ldap"
                    }
                ]
----
====



* HealthcareService.specialty - See simplifier profile for possible values.

.Example data:
[%collapsible%open]
====
[source,txt, linenums]
----
                "specialty": [
                    {
                        "coding": [
                            {
                                "system": "https://gematik.de/fhir/directory/CodeSystem/PharmacyHealthcareSpecialtyCS",
                                "code": "30",
                                "display": "Botendienst"
                            },
                            {
                                "system": "https://gematik.de/fhir/directory/CodeSystem/PharmacyHealthcareSpecialtyCS",
                                "code": "10",
                                "display": "Handverkauf"
                            },
                            {
                                "system": "https://gematik.de/fhir/directory/CodeSystem/PharmacyHealthcareSpecialtyCS",
                                "code": "40",
                                "display": "Versand"
                            }
                        ],
                        "text": "apo-vzd"
                    },
                    {
                        "coding": [
                            {
                                "system": "https://gematik.de/fhir/directory/CodeSystem/PharmacyHealthcareSpecialtyCS",
                                "code": "10",
                                "display": "Handverkauf"
                            }
                        ],
                        "text": "ldap"
                    }
                ]
----
====

* HealthcareService.characteristic - Physical Features & Technical Services - See simplifier profile for possible values.


*Contact details* +
 +
How to contact the pharmacy can be administrated.

Used FHIR VZD attributes: +

* HealthcareService.telecom - See simplifier profile for possible values.

.Example data:
[%collapsible%open]
====
[source,txt, linenums]
----
                "telecom": [
                    {
                        "system": "phone",
                        "value": "030 1234567",
                        "rank": 10
                    },
                    {
                        "system": "fax",
                        "value": "030 1234568",
                        "rank": 20
                    },
                    {
                        "system": "email",
                        "value": "info@apotheke.de",
                        "rank": 30
                    },
                    {
                        "system": "url",
                        "value": "https://www.apotheke.de",
                        "rank": 40
                    }
                ]

----
====




*Delivery area* +
 +
The area in which the pharmacy offers "Botendienste". +
 +
Used FHIR VZD attributes: +

* HealthcareService.coverageArea - See simplifier profile for possible values.

.Example data:
[%collapsible%open]
====
[source,txt, linenums]
----
                "coverageArea": [
                    {
                        "extension": [
                            {
                                "url": "https://gematik.de/fhir/directory/StructureDefinition/ServiceCoverageArea",
                                "valueQuantity": {
                                    "value": 15000,
                                    "system": "http://unitsofmeasure.org",
                                    "code": "m"
                                }
                            }
                        ]
                    }
                ]
----
====
// To be added: PLZ


*Geographical coordinates* +
 +
Used in the eRezept Apps for feature "Umkeissuche". +
 +
Used FHIR VZD attributes: +

* Location.position - See simplifier profile for possible values.

.Example data:
[%collapsible%open]
====
[source,txt, linenums]
----
                "position": {
                    "longitude": 8.087935,
                    "latitude": 51.086569
                }
----
====



*Opening hours* +
 +
The opening hours of the pharmacy.

Used FHIR VZD attributes: +

* HealthcareService.availableTime - See simplifier profile for possible values.

.Example data:
[%collapsible%open]
====
[source,txt, linenums]
----
                "availableTime": [
                    {
                        "daysOfWeek": [
                            "mon"
                        ],
                        "availableStartTime": "08:00:00",
                        "availableEndTime": "13:00:00"
                    },
                    {
                        "daysOfWeek": [
                            "mon"
                        ],
                        "availableStartTime": "14:00:00",
                        "availableEndTime": "18:30:00"
                    },
                    {
                        "daysOfWeek": [
                            "tue"
                        ],
                        "availableStartTime": "08:00:00",
                        "availableEndTime": "13:00:00"
                    },
                    {
                        "daysOfWeek": [
                            "tue"
                        ],
                        "availableStartTime": "14:00:00",
                        "availableEndTime": "18:30:00"
                    },
                    {
                        "daysOfWeek": [
                            "wed"
                        ],
                        "availableStartTime": "08:00:00",
                        "availableEndTime": "13:00:00"
                    },
                    {
                        "daysOfWeek": [
                            "wed"
                        ],
                        "availableStartTime": "14:00:00",
                        "availableEndTime": "18:30:00"
                    },
                    {
                        "daysOfWeek": [
                            "thu"
                        ],
                        "availableStartTime": "08:00:00",
                        "availableEndTime": "13:00:00"
                    },
                    {
                        "daysOfWeek": [
                            "thu"
                        ],
                        "availableStartTime": "14:00:00",
                        "availableEndTime": "18:30:00"
                    },
                    {
                        "daysOfWeek": [
                            "fri"
                        ],
                        "availableStartTime": "08:00:00",
                        "availableEndTime": "13:00:00"
                    },
                    {
                        "daysOfWeek": [
                            "fri"
                        ],
                        "availableStartTime": "14:00:00",
                        "availableEndTime": "18:30:00"
                    },
                    {
                        "daysOfWeek": [
                            "sat"
                        ],
                        "availableStartTime": "08:30:00",
                        "availableEndTime": "13:00:00"
                    }
                ],
----
====




*Visibility of the pharmacy for insured persons* +
 +
If a pharmacy does not offer services for insured people, it can be hidden from the insured apps. 

- Used FHIR VZD attribute: Organization.extension:organizationVisibility
- link:https://github.com/gematik/api-vzd/blob/feature/gemILF_VZD_FHIR_Directory/docs/FHIR_VZD_HOWTO_UseCases.adoc#organization---set-organizationvisibility[Update Example]




==== Update FHIR VZD resource
Examples for FHIR operations to update the resource in the FHIR VZD. +

===== Organization - set organizationVisibility
The following example updates attribute organizationVisibility of an Organization resource (this organization will be not found in the /fdv/search interface).

.Request
[source]
----
PUT https://fhir-directory-test.vzd.ti-dienste.de/owner/Organization/824d25e9-7fa7-4628-bdb1-62a54f83eae2
----

.Request Body
[source]
----
{
    "resourceType": "Organization",
    "id": "824d25e9-7fa7-4628-bdb1-62a54f83eae2",
    "meta": {
        "versionId": "1",
        "lastUpdated": "2025-03-06T08:39:43.819+01:00",
        "source": "#vE5dZwUVTBZFbPE1",
        "profile": [
            "https://gematik.de/fhir/directory/StructureDefinition/OrganizationDirectory"
        ],
        "tag": [
            {
                "system": "https://gematik.de/fhir/directory/CodeSystem/Origin",
                "code": "ldap",
                "display": "Synchronized from LDAP VZD"
            }
        ]
    },
    "extension": [
        {
            "url": "https://gematik.de/fhir/directory/StructureDefinition/OrganizationVisibility",
            "valueCoding": {
                "system": "https://gematik.de/fhir/directory/CodeSystem/OrganizationVisibilityCS",
                "code": "hide-versicherte"
            }
        }
    ],
    "identifier": [
        {
            "system": "http://hl7.org/fhir/sid/us-npi",
            "value": "b1c20438-60ad-4759-9f9b-287958b57e2b"
        },
        {
            "type": {
                "coding": [
                    {
                        "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
                        "code": "PRN"
                    }
                ]
            },
            "system": "https://gematik.de/fhir/sid/telematik-id",
            "value": "1-20410167346"
        },
        {
            "system": "https://gematik.de/fhir/directory/CodeSystem/ldapUID",
            "value": "aa6d339b-83dd-4e55-a600-692e7dff1d1d"
        }
    ],
    "active": true,
    "type": [
        {
            "coding": [
                {
                    "system": "https://gematik.de/fhir/directory/CodeSystem/OrganizationProfessionOID",
                    "code": "1.2.276.0.76.4.54",
                    "display": "Öffentliche Apotheke"
                }
            ]
        }
    ],
    "name": "Berufsausübungsgemeinschaft Dr. Melina Harlaß",
    "alias": [
        "Apo Harlaß"
    ]
}

----

===== Endpoint - set endpointVisibility
The following example updates attribute endpointVisibility of an Endpoint resource (this endpoint will be not found in the /fdv/search interface).

.Request
[source]
----
PUT https://fhir-directory-test.vzd.ti-dienste.de/owner/Endpoint/035c6e2c-53f8-4a35-925b-b87303b07b6d
----

.Request Body
[source]
----
{
    "resourceType": "Endpoint",
    "id": "035c6e2c-53f8-4a35-925b-b87303b07b6d",
    "meta": {
        "versionId": "1",
        "lastUpdated": "2025-02-14T09:24:13.129+01:00",
        "source": "#39ToGeHsLcqR31iG",
        "profile": [
            "https://gematik.de/fhir/directory/StructureDefinition/EndpointDirectory"
        ],
        "tag": [
            {
                "system": "https://gematik.de/fhir/directory/CodeSystem/Origin",
                "code": "owner"
            },
            {
                "system": "https://gematik.de/fhir/directory/source",
                "code": "ARV-TDG-20250213"
            }
        ]
    },
    "identifier": [
        {
            "system": "http://hl7.org/fhir/sid/us-npi",
            "value": "793858ee-f6e3-4edd-ba72-2d80a1ee281a"
        }
    ],
    "extension": [
        {
            "url": "https://gematik.de/fhir/directory/StructureDefinition/EndpointVisibility",
            "valueCoding": {
                "code": "hide-versicherte",
                "system": "https://gematik.de/fhir/directory/CodeSystem/EndpointVisibilityCS"
            }
        }
    ],
    "status": "active",
    "connectionType": {
        "system": "https://gematik.de/fhir/directory/CodeSystem/EndpointDirectoryConnectionType",
        "code": "tim"
    },
    "name": "MatrixId von Organisation 5-2-ARV1663735100000000 (matrix:u/5-2-ARV1663735100000000:tim.test.gematik.de)",
    "payloadType": [
        {
            "coding": [
                {
                    "system": "https://gematik.de/fhir/directory/CodeSystem/EndpointDirectoryPayloadType",
                    "code": "tim-chat",
                    "display": "TI-Messenger chat"
                }
            ]
        }
    ],
    "address": "matrix:u/5-2-ARV1663735100000000:tim.test.gematik.de"
}

----

=== FHIR VZD pharmacy Example Data 
==== Offizin-Apotheke with "Botendienst" & "Handverkauf"

.Organization
[%collapsible%open]
====
[source,txt, linenums]
----
 {
  "resourceType": "Organization",
  "id": "75b8b2ar-5d81-7ct6-b535-f7fc78f5596c",
  "meta": {
    "versionId": "2",
    "lastUpdated": "2025-03-23T01:12:37.167+02:00",
    "source": "#8Bz25c6HiWzXwkWo",
    "profile": [
      "https://gematik.de/fhir/directory/StructureDefinition/OrganizationDirectory"
    ],
    "tag": [
      {
        "system": "https://gematik.de/fhir/directory/CodeSystem/Origin",
        "code": "ldap",
        "display": "Synchronized from LDAP VZD",
        "userSelected": false
      }
    ]
  },
  "identifier": [
    {
      "type": {
        "coding": [
          {
            "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
            "code": "PRN"
          }
        ]
      },
      "system": "https://gematik.de/fhir/sid/telematik-id",
      "value": "3-01.2.1113332066.279"
    },
    {
      "system": "https://gematik.de/fhir/directory/CodeSystem/ldapUID",
      "value": "ag24e566-8w3e-471c-8309-7ef35905972a"
    }
  ],
  "active": true,
  "type": [
    {
      "coding": [
        {
          "system": "https://gematik.de/fhir/directory/CodeSystem/OrganizationProfessionOID",
          "code": "1.2.276.0.76.4.54",
          "display": "Öffentliche Apotheke"
        }
      ]
    }
  ],
  "name": "Alte-Apotheke"
} 
----
====

.Healthcare Service
[%collapsible%open]
====
[source,txt, linenums]
----
 {
  "resourceType": "HealthcareService",
  "id": "db27d0fe-b4z3-4e6d-88ee-829f89052603",
  "meta": {
    "versionId": "4",
    "lastUpdated": "2025-03-25T10:25:59.944+02:00",
    "source": "#iHGPLXQ8CxPXzfdC",
    "profile": [
      "https://gematik.de/fhir/directory/StructureDefinition/HealthcareServiceDirectory"
    ],
    "tag": [
      {
        "system": "https://gematik.de/fhir/directory/CodeSystem/Origin",
        "code": "ldap",
        "display": "Synchronized from LDAP VZD",
        "userSelected": false
      }
    ]
  },
  "identifier": [
    {
      "system": "https://gematik.de/fhir/directory/CodeSystem/ldapUID",
      "value": "ag24e566-8w3e-471c-8309-7ef35905972a"
    }
  ],
  "providedBy": {
    "reference": "Organization/76b8a2ac-4d61-4cf6-b555-f2fc75f5566b"
  },
  "type": [
    {
      "coding": [
        {
          "system": "https://gematik.de/fhir/directory/CodeSystem/PharmacyTypeCS",
          "code": "offizin-apotheke",
          "display": "Offizin-Apotheke"
        }
      ],
      "text": "apo-vzd"
    },
    {
      "coding": [
        {
          "system": "https://gematik.de/fhir/directory/CodeSystem/PharmacyTypeCS",
          "code": "offizin-apotheke",
          "display": "Offizin-Apotheke"
        }
      ],
      "text": "ldap"
    }
  ],
  "specialty": [
    {
      "coding": [
        {
          "system": "https://gematik.de/fhir/directory/CodeSystem/PharmacyHealthcareSpecialtyCS",
          "code": "30",
          "display": "Botendienst"
        },
        {
          "system": "https://gematik.de/fhir/directory/CodeSystem/PharmacyHealthcareSpecialtyCS",
          "code": "10",
          "display": "Handverkauf"
        }
      ],
      "text": "apo-vzd"
    },
    {
      "coding": [
        {
          "system": "https://gematik.de/fhir/directory/CodeSystem/PharmacyHealthcareSpecialtyCS",
          "code": "10",
          "display": "Handverkauf"
        }
      ],
      "text": "ldap"
    }
  ],
  "location": [
    {
      "reference": "Location/69ec3cc9-dad6-4b0d-ad34-816d1774fc11"
    }
  ],
  "telecom": [
    {
      "system": "phone",
      "value": "0301234567",
      "rank": 10
    },
    {
      "system": "fax",
      "value": "0301234568",
      "rank": 20
    },
    {
      "system": "email",
      "value": "info@apotheke.de",
      "rank": 30
    },
    {
      "system": "url",
      "value": "http://www.apotheke.com",
      "rank": 40
    }
  ],
  "coverageArea": [
    {
      "extension": [
        {
          "url": "https://gematik.de/fhir/directory/StructureDefinition/ServiceCoverageArea",
          "valueQuantity": {
            "value": 5000,
            "system": "http://unitsofmeasure.org",
            "code": "m"
          }
        }
      ]
    }
  ],
  "availableTime": [
    {
      "daysOfWeek": [
        "mon"
      ],
      "availableStartTime": "08:30:00",
      "availableEndTime": "12:30:00"
    },
    {
      "daysOfWeek": [
        "mon"
      ],
      "availableStartTime": "14:00:00",
      "availableEndTime": "18:30:00"
    },
    {
      "daysOfWeek": [
        "tue"
      ],
      "availableStartTime": "08:30:00",
      "availableEndTime": "12:30:00"
    },
    {
      "daysOfWeek": [
        "tue"
      ],
      "availableStartTime": "14:00:00",
      "availableEndTime": "18:30:00"
    },
    {
      "daysOfWeek": [
        "wed"
      ],
      "availableStartTime": "08:30:00",
      "availableEndTime": "12:30:00"
    },
    {
      "daysOfWeek": [
        "wed"
      ],
      "availableStartTime": "14:00:00",
      "availableEndTime": "18:30:00"
    },
    {
      "daysOfWeek": [
        "thu"
      ],
      "availableStartTime": "08:30:00",
      "availableEndTime": "12:30:00"
    },
    {
      "daysOfWeek": [
        "thu"
      ],
      "availableStartTime": "14:00:00",
      "availableEndTime": "18:30:00"
    },
    {
      "daysOfWeek": [
        "fri"
      ],
      "availableStartTime": "08:30:00",
      "availableEndTime": "12:30:00"
    },
    {
      "daysOfWeek": [
        "fri"
      ],
      "availableStartTime": "14:00:00",
      "availableEndTime": "18:30:00"
    },
    {
      "daysOfWeek": [
        "sat"
      ],
      "availableStartTime": "09:30:00",
      "availableEndTime": "12:30:00"
    }
  ]
} 
----
====

.Location
[%collapsible%open]
====
[source,txt, linenums]
----
  {
  "resourceType": "Location",
  "id": "65eh3cu9-ded7-6b2d-ar32-876d1974fd12",
  "meta": {
    "versionId": "2",
    "lastUpdated": "2025-03-13T10:16:20.003+02:00",
    "source": "#S3aH7F3GHryuIuOZ",
    "profile": [
      "https://gematik.de/fhir/directory/StructureDefinition/LocationDirectory"
    ],
    "tag": [
      {
        "system": "https://gematik.de/fhir/directory/CodeSystem/Origin",
        "code": "ldap",
        "display": "Synchronized from LDAP VZD",
        "userSelected": false
      }
    ]
  },
  "identifier": [
    {
      "system": "https://gematik.de/fhir/directory/CodeSystem/ldapUID",
      "value": "ag24e566-8w3e-471c-8309-7ef35905972a"
    }
  ],
  "address": {
    "use": "work",
    "type": "postal",
    "text": "Königstraße 56&#13;&#10;15732&#13;&#10;Schulzendorf&#13;&#10;Brandenburg&#13;&#10;DE",
    "line": [
      "Königstraße 56"
    ],
    "city": "Schulzendorf",
    "state": "Brandenburg",
    "postalCode": "15732",
    "country": "DE"
  },
  "position": {
    "longitude": 9.304613,
    "latitude": 48.682805
  }
} 
----
====

//  Beispielapozheke 2
==== Offizin-Apotheke with "Botendienst" & "Handverkauf" & Data for feature "Zuweisen ohne Anmelden"

.Organization
[%collapsible%open]
====
[source,txt, linenums]
----
           {
                "resourceType": "Organization",
                "id": "bb085c88-7ddc-40ef-8600-a1a1fe0f7dd9",
                "meta": {
                    "versionId": "3",
                    "lastUpdated": "2025-03-07T11:57:52.649+01:00",
                    "source": "#PiPeUk3VIFLLKCZU",
                    "profile": [
                        "https://gematik.de/fhir/directory/StructureDefinition/OrganizationDirectory"
                    ],
                    "tag": [
                        {
                            "system": "https://gematik.de/fhir/directory/CodeSystem/Origin",
                            "code": "ldap",
                            "display": "Synchronized from LDAP VZD"
                        }
                    ]
                },
                "identifier": [
                    {
                        "type": {
                            "coding": [
                                {
                                    "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
                                    "code": "PRN"
                                }
                            ]
                        },
                        "system": "https://gematik.de/fhir/sid/telematik-id",
                        "value": "3-11.2.0000655905.726"
                    },
                    {
                        "system": "https://gematik.de/fhir/directory/CodeSystem/ldapUID",
                        "value": "88526918-46ca-4b5z-9adb-347aiab39jdb"
                    }
                ],
                "active": true,
                "type": [
                    {
                        "coding": [
                            {
                                "system": "https://gematik.de/fhir/directory/CodeSystem/OrganizationProfessionOID",
                                "code": "1.2.276.0.76.4.54",
                                "display": "Öffentliche Apotheke"
                            }
                        ]
                    }
                ],
                "name": "Deutsche-Apotheke"
            }
----
====

.Healthcare Service
[%collapsible%open]
====
[source,txt, linenums]
----
            {
                "resourceType": "HealthcareService",
                "id": "527d1ca8-eb54-4487-8718-e2e6abe4962b",
                "meta": {
                    "versionId": "9",
                    "lastUpdated": "2025-03-20T03:03:43.604+01:00",
                    "source": "#BJN6PvHJtfROlkVA",
                    "profile": [
                        "https://gematik.de/fhir/directory/StructureDefinition/HealthcareServiceDirectory"
                    ],
                    "tag": [
                        {
                            "system": "https://gematik.de/fhir/directory/CodeSystem/Origin",
                            "code": "ldap",
                            "display": "Synchronized from LDAP VZD"
                        }
                    ]
                },
                "identifier": [
                    {
                        "system": "https://gematik.de/fhir/directory/CodeSystem/ldapUID",
                        "value": "88526918-46ca-4b5z-9adb-347aiab39jdb"
                    }
                ],
                "providedBy": {
                    "reference": "Organization/bb085c88-7ddc-40ef-8600-a1a1fe0f7dd9"
                },
                "type": [
                    {
                        "coding": [
                            {
                                "system": "https://gematik.de/fhir/directory/CodeSystem/PharmacyTypeCS",
                                "code": "offizin-apotheke",
                                "display": "Offizin-Apotheke"
                            }
                        ],
                        "text": "apo-vzd"
                    },
                    {
                        "coding": [
                            {
                                "system": "https://gematik.de/fhir/directory/CodeSystem/PharmacyTypeCS",
                                "code": "offizin-apotheke",
                                "display": "Offizin-Apotheke"
                            }
                        ],
                        "text": "ldap"
                    }
                ],
                "specialty": [
                    {
                        "coding": [
                            {
                                "system": "https://gematik.de/fhir/directory/CodeSystem/PharmacyHealthcareSpecialtyCS",
                                "code": "30",
                                "display": "Botendienst"
                            },
                            {
                                "system": "https://gematik.de/fhir/directory/CodeSystem/PharmacyHealthcareSpecialtyCS",
                                "code": "10",
                                "display": "Handverkauf"
                            }
                        ],
                        "text": "apo-vzd"
                    },
                    {
                        "coding": [
                            {
                                "system": "https://gematik.de/fhir/directory/CodeSystem/PharmacyHealthcareSpecialtyCS",
                                "code": "10",
                                "display": "Handverkauf"
                            }
                        ],
                        "text": "ldap"
                    }
                ],
                "location": [
                    {
                        "reference": "Location/91357b39-05c4-4eb7-8252-d58e27497c1a"
                    }
                ],
                "telecom": [
                    {
                        "system": "phone",
                        "value": "030-12345678",
                        "rank": 10
                    },
                    {
                        "system": "fax",
                        "value": "030-12345679",
                        "rank": 20
                    },
                    {
                        "system": "email",
                        "value": "info@deutsche-apotheke.de",
                        "rank": 30
                    },
                    {
                        "system": "url",
                        "value": "https://www.deutsche-apotheke.de",
                        "rank": 40
                    }
                ],
                "coverageArea": [
                    {
                        "extension": [
                            {
                                "url": "https://gematik.de/fhir/directory/StructureDefinition/ServiceCoverageArea",
                                "valueQuantity": {
                                    "value": 10000,
                                    "system": "http://unitsofmeasure.org",
                                    "code": "m"
                                }
                            }
                        ]
                    }
                ],
                "availableTime": [
                    {
                        "daysOfWeek": [
                            "mon"
                        ],
                        "availableStartTime": "08:00:00",
                        "availableEndTime": "12:30:00"
                    },
                    {
                        "daysOfWeek": [
                            "mon"
                        ],
                        "availableStartTime": "14:00:00",
                        "availableEndTime": "18:00:00"
                    },
                    {
                        "daysOfWeek": [
                            "tue"
                        ],
                        "availableStartTime": "08:00:00",
                        "availableEndTime": "12:30:00"
                    },
                    {
                        "daysOfWeek": [
                            "tue"
                        ],
                        "availableStartTime": "14:00:00",
                        "availableEndTime": "18:00:00"
                    },
                    {
                        "daysOfWeek": [
                            "wed"
                        ],
                        "availableStartTime": "08:00:00",
                        "availableEndTime": "12:30:00"
                    },
                    {
                        "daysOfWeek": [
                            "thu"
                        ],
                        "availableStartTime": "08:00:00",
                        "availableEndTime": "12:30:00"
                    },
                    {
                        "daysOfWeek": [
                            "thu"
                        ],
                        "availableStartTime": "14:00:00",
                        "availableEndTime": "18:00:00"
                    },
                    {
                        "daysOfWeek": [
                            "fri"
                        ],
                        "availableStartTime": "08:00:00",
                        "availableEndTime": "12:30:00"
                    },
                    {
                        "daysOfWeek": [
                            "fri"
                        ],
                        "availableStartTime": "14:00:00",
                        "availableEndTime": "18:00:00"
                    },
                    {
                        "daysOfWeek": [
                            "sat"
                        ],
                        "availableStartTime": "08:30:00",
                        "availableEndTime": "12:00:00"
                    }
                ],
                "endpoint": [
                    {
                        "reference": "Endpoint/c6fee28a-6c4f-4d8f-adfc-7be1880d6c8a"
                    },
                    {
                        "reference": "Endpoint/9de10dc1-4301-4635-b0c1-2f75fba51b14"
                    }
                ]
            }
----
====

.Location
[%collapsible%open]
====
[source,txt, linenums]
----
           {
                "resourceType": "Location",
                "id": "91357b39-05c4-4eb7-8252-d58e27497c1a",
                "meta": {
                    "versionId": "4",
                    "lastUpdated": "2025-02-07T11:57:52.649+01:00",
                    "source": "#PiPtUj3VIFLLKDCU",
                    "profile": [
                        "https://gematik.de/fhir/directory/StructureDefinition/LocationDirectory"
                    ],
                    "tag": [
                        {
                            "system": "https://gematik.de/fhir/directory/CodeSystem/Origin",
                            "code": "ldap",
                            "display": "Synchronized from LDAP VZD"
                        }
                    ]
                },
                "identifier": [
                    {
                        "system": "https://gematik.de/fhir/directory/CodeSystem/ldapUID",
                        "value": "88526918-46ca-4b5z-9adb-347aiab39jdb"
                    }
                ],
                "address": {
                    "use": "work",
                    "type": "postal",
                    "text": "Hauptstraße 19&#13;&#10;66882&#13;&#10;Berlin&#13;&#10;Berlin&#13;&#10;DE",
                    "line": [
                        "Hauptstraße 19"
                    ],
                    "city": "Berlin",
                    "state": "Berlin",
                    "postalCode": "10117",
                    "country": "DE"
                },
                "position": {
                    "longitude": 7.874927,
                    "latitude": 49.518826
                }
            }
----
====

.Endpoint 1 "eRP-delivery"
[%collapsible%open]
====
[source,txt, linenums]
----
            {
                "resourceType": "Endpoint",
                "id": "9de10dc1-4301-4635-b0c1-2f75fba51b14",
                "meta": {
                    "versionId": "1",
                    "lastUpdated": "2025-03-20T03:03:43.549+01:00",
                    "source": "#W81xNuDY9TwsTSC9",
                    "profile": [
                        "https://gematik.de/fhir/directory/StructureDefinition/EndpointDirectory"
                    ],
                    "tag": [
                        {
                            "system": "https://gematik.de/fhir/directory/CodeSystem/Origin",
                            "code": "apo"
                        }
                    ]
                },
                "identifier": [
                    {
                        "system": "https://gematik.de/fhir/sid/telematik-id",
                        "value": "3-11.2.0000655905.726"
                    }
                ],
                "status": "active",
                "connectionType": {
                    "system": "https://gematik.de/fhir/directory/CodeSystem/EndpointDirectoryConnectionType",
                    "code": "eRP-delivery"
                },
                "name": "eRP-delivery",
                "payloadType": [
                    {
                        "coding": [
                            {
                                "system": "http://terminology.hl7.org/CodeSystem/data-absent-reason",
                                "code": "not-applicable"
                            }
                        ]
                    }
                ],
                "address": "https://ixosapi.service-pt.de/api/GematikAppZuweisung/544566?sig=TiHnTBHTqJwq6NGO3iqDcGBTYGVf%2bBnQAVGPBAz8ZVs%3d&se=2606242634"
            }
----
====

.Endpoint 2 "eRP-onPremise"
[%collapsible%open]
====
[source,txt, linenums]
----
            {
                "resourceType": "Endpoint",
                "id": "c6fee28a-6c4f-4d8f-adfc-7be1880d6c8a",
                "meta": {
                    "versionId": "1",
                    "lastUpdated": "2025-02-20T03:03:43.498+01:00",
                    "source": "#nMr3Dn0ZYP6Lcta2",
                    "profile": [
                        "https://gematik.de/fhir/directory/StructureDefinition/EndpointDirectory"
                    ],
                    "tag": [
                        {
                            "system": "https://gematik.de/fhir/directory/CodeSystem/Origin",
                            "code": "apo"
                        }
                    ]
                },
                "identifier": [
                    {
                        "system": "https://gematik.de/fhir/sid/telematik-id",
                        "value": "3-11.2.0000655905.726"
                    }
                ],
                "status": "active",
                "connectionType": {
                    "system": "https://gematik.de/fhir/directory/CodeSystem/EndpointDirectoryConnectionType",
                    "code": "eRP-onPremise"
                },
                "name": "eRP-onPremise",
                "payloadType": [
                    {
                        "coding": [
                            {
                                "system": "http://terminology.hl7.org/CodeSystem/data-absent-reason",
                                "code": "not-applicable"
                            }
                        ]
                    }
                ],
                "address": "https://ixosapi.service-pt.de/api/GematikAppZuweisung/544466?sig=TiHnTBHTqJeq6NGO3iqDcGBTYVVf%2bBnQAVGPBAz8ZVs%3d&se=2601642634"
            }
----
====


