= FHIR VZD HOWTO UseCases
:source-highlighter: rouge
:icons:
:title-page:
:imagesdir: /images/
ifdef::env-github[]
:toc: preamble
endif::[]
ifndef::env-github[]
:toc: left
endif::[]
:toclevels: 3
:toc-title: Table of Contents
:sectnums:


image::gematik_logo.svg[gematik,float="right"]

[width="100%",cols="50%,50%",options="header",]
|===
|Version: |0.0.1
|Referencing: |gemILF_FHIR_VZD
|===

[big]*Document history*

[width="100%",cols="11%,11%,7%,58%,13%",options="header",]
|===
|*Version* +
 |*Stand* +
 |*Chap./ Page* +
 |*Change reason, special instructions* +
 |*Editing* +

|0.0.1 |14.03.25 | |Initial document |gematik

|===

== Classification of the document
=== Objective
This document sums up examples in interacting with the FHIR VZD. 

=== Target group

The document is aimed at software developers who are involved in implementing a client that interacts with the APIs of the VZD-FHIR-Directory.

=== Scope

*Intellectual property/patent notice*

_The following specification was created by gematik solely from a technical point of view. In individual cases, it cannot be ruled out that the implementation of the specification will interfere with the technical property rights of third parties. It is solely up to the supplier or manufacturer to take suitable measures to ensure that the products and/or services offered by him on the basis of the specification do not infringe third-party property rights and, if necessary, to obtain the necessary permits/licenses from the property right holders concerned. In this respect, gematik GmbH assumes no liability whatsoever._


== Administration of value-added data by the owner of the FHIR VZD Entry
The VZD Entries are administrated by the responsible healthcare organizations. Some value-added data can be administrated by the owner of the FHIR VZD Entry.
The link:FHIR_VZD_HOWTO_Data.adoc#directory-of-organizations[FHIR VZD data model] describes which data the owner can maintain himself (column "Changable by owner" in the tables). +
This section describes how to implement the administration of value-added data in the client (e.g. PVS/AVS/...).

=== Authentication
The value-added data is administrated via the FHIR VZD /owner interface.
To access the /owner API a valid provider access_token is needed that can be obtained by authenticating via the following via one of the following options

- link:FHIR_VZD_HOWTO_Authenticate.adoc#24-authenticate-for-the-owner-endpoint-as-an-user[Authenticate for the /owner interface by using a smartcard (HBA/SMC-B)]. This has to be the smartcard with the telematikID of the FHIR VZD Entry which is changed. An option is, to link:FHIR_VZD_HOWTO_Authenticate.adoc#25-authenticate-using-the-gematik-authenticator[use the gematik Authenticator]  simplify the interaction with a connector, the card terminals and the users smartcards.

- If the FHIR VZD Organization Entry owns a TIM domain, then the  link:FHIR_VZD_HOWTO_Authenticate.adoc#23-authenticate-for-the-owner-endpoint-as-an-organization[Authenticate for the /owner interface as an organization] authentication can be used.

[NOTE]
====
You can find sample code for the authentication here link:https://github.com/gematik/api-vzd/tree/main/samples/directory-samples-java/auth-samples[Java sample] 
and here link:https://github.com/gematik/api-vzd/tree/main/samples/directory-samples-python/directory_samples[Python sample]
====

=== Administration of value-added data
==== Search
First you have to find the resource instance. Use the operations, described in the link:FHIR_VZD_HOWTO_Search.adoc[FHIR VZD HOWTO Search]. +
In the search result the resource data is contained.

==== Change data
Which attributes of which resources can be added or modified is described in the link:FHIR_VZD_HOWTO_Data.adoc[FHIR VZD data model]. +
The simplifier profile of the FHIR VZD can be found here link:https://simplifier.net/vzd-fhir-directory[gematik FHIR Directory].

[IMPORTANT]
====
The client has to ensure, that the telematikID of the resource instance (or its superior Organization/Practitioner resource) and the token (see step "Authentication) match. The FHIR VZD will deny all write operations for resources with other telematikIDs. +
====
==== Update FHIR VZD resource
Use a FHIR operation to update the resource in the FHIR VZD. +
 + 
The following expamle updates attribute organizationVisibility of an Organization resource (this organization will be not found in the /fdv/search interface). 

.Request
[source]
----
PUT https://fhir-directory-test.vzd.ti-dienste.de/owner/Organization/824d25e9-7fa7-4628-bdb1-62a54f83eae2
----

.Request Body
[source]
----
{
                "resourceType": "Organization",
                "id": "824d25e9-7fa7-4628-bdb1-62a54f83eae2",
                "meta": {
                    "versionId": "1",
                    "lastUpdated": "2025-03-06T08:39:43.819+01:00",
                    "source": "#vE5dZwUVTBZFbPE1",
                    "profile": [
                        "https://gematik.de/fhir/directory/StructureDefinition/OrganizationDirectory"
                    ],
                    "tag": [
                        {
                            "system": "https://gematik.de/fhir/directory/CodeSystem/Origin",
                            "code": "ldap",
                            "display": "Synchronized from LDAP VZD"
                        }
                    ]
                },
                "extension": [
                    {
                        "url": "https://gematik.de/fhir/directory/StructureDefinition/OrganizationVisibility",
                        "valueCoding": {
                            "system": "https://gematik.de/fhir/directory/CodeSystem/OrganizationVisibilityCS",
                            "code": "hide-versicherte"
                        }
                    }
                ],
                "identifier": [
                    {
                        "system": "http://hl7.org/fhir/sid/us-npi",
                        "value": "b1c20438-60ad-4759-9f9b-287958b57e2b"
                    },
                    {
                        "type": {
                            "coding": [
                                {
                                    "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
                                    "code": "PRN"
                                }
                            ]
                        },
                        "system": "https://gematik.de/fhir/sid/telematik-id",
                        "value": "1-20410167346"
                    },
                    {
                        "system": "https://gematik.de/fhir/directory/CodeSystem/ldapUID",
                        "value": "aa6d339b-83dd-4e55-a600-692e7dff1d1d"
                    }
                ],
                "active": true,
                "type": [
                    {
                        "coding": [
                            {
                                "system": "https://gematik.de/fhir/directory/CodeSystem/OrganizationProfessionOID",
                                "code": "1.2.276.0.76.4.54",
                                "display": "Öffentliche Apotheke"
                            }
                        ]
                    }
                ],
                "name": "Berufsausübungsgemeinschaft Dr. Melina Harlaß",
                "alias": [
                    "Apo Harlaß"
                ]
            }

----

