= 🗂️ LDAP-Attribute im gematik Verzeichnisdienst
:toc:
:toc-title: Inhaltsverzeichnis
:sectnums:
:note-caption: ℹ️

== Übersicht

[%autowidth.stretch]
|===
| Attribut | 0..N | Bezeichnung

3+s|Identifikatoren

m| <<telematikID>>
| 1..1
| Telematik-ID

m| <<domainID>>
| 1..N
| Sektor-ID

3+s|Namen
m| <<displayName>>
| 1..1
| Anzeigename
m| <<cn>>
| 1..1
| Name
m| <<otherName>>
| 0..1
| Alternativer Name
m| <<organization>>
| 0..1
| Organisation
m| <<givenName>>
| 0..1
| Vorname
m| <<sn>>
| 0..1
| Nachname
m| <<title>>
| 0..1
| Titel

3+s|Adressdaten
m| <<streetAddress>>
| 1..1
| Straße und Hausnummer
m| <<postalCode>>
| 1..1
| PLZ
m| <<localityName>>
| 1..1
| Ort
m| <<stateOrProvinceName>>
| 1..1
| Bundesland oder Region
m| <<countryCode>>
| 1..1
| Landeskürzel

3+s|Berufliche Informationen
m| <<professionOID>>
| 1..N
| Berufsgruppe
m| <<specialization>>
| 1..N
| Fachgebiet
m| <<entryType>>
| 1..1
| Typ des Eintags
m| <<lanr>>
| 0..N
| Lebenslange Arztnummer

3+s|Anwendungsdaten
m| <<mail>>
| 0..N
| KIM-Adresse

m| <<komLeData>>
| 0..N
| KIM-Adresse mit Version

m| <<kimData>>
| 0..N
| KIM-Adresse mit Version

m| <<maxKOMLEadr>>
| 0..1
| Maximale Anzahl von KIM-Adressen in den KOM-LE-Fachdaten

3+s|Zertifikate
m| <<userCertificate>>
| 0..N
| Zertifikat

m| <<notBefore>>
| 0..1
| Gültigkeitsbeginn Zertifikat

m| <<userCertificate.active>>
| 0..1
| Zertifikat gültig?

m| <<notAfter>>
| 0..1
| Gültigkeitsende Zertifikat

m| <<serialNumber>>
| 0..1
| Seriennummer des Zertifikats

m| <<issuer>>
| 0..1
| Zertifikatsaussteller

m| <<publicKeyAlgorithm>>
| 0..1
| Verschlüsselungsalgorithmus des Zertifikats



3+s|Systemdaten
m| <<dataFromAuthority>>
| 1..1
| Verwaltet durch Kartenherausgeber?
m| <<personalEntry>>
| 1..1
| Eintrag einer natürlichen Person?
m| <<changeDateTime>>
| 1..1
| Geändert am
m| <<active>>
| 1..1
| Eintrag aktiv?
m| <<meta>>
| 0..100
| Abstimmung zwischen TSP und Kartenherausgeber

|===

== Identifikatoren

=== telematikID

Telematik-ID ist ein eindeutiger Identifikator einer Institution oder einer Person in der TI.
Spezifiziert in https://fachportal.gematik.de/fachportal-import/files/gemSpec_PKI_V2.11.1.pdf[gemSpec_PKI], Kapitel 4.7.

=== domainID

Die sektorspezifische Kennung einer Institution oder einer Person.

Per Eintag können mehrere Kennungen angeben werden. Im Gegensatz zu TelematikID sind die `domainID` nicht eindeutig können in mehreren Einträgen gleichzeitig vorkommen.

Die Nutzung für die Sektoren wird in Kapitel *Attributtabellen* von Dokument https://fachportal.gematik.de/fileadmin/Fachportal/Downloadcenter/Implementierungsleitfaeden/gemILF_Pflege_VZD_V1.5.1.pdf[gemILF_Pflege_VZD] beschrieben.

* Kassenärztliche Vereinigungen (SMC-B-Eintrag): Betriebsstättennummer der Praxis
* Kassenzahnärztliche Vereinigungen (SMC-B Eintrag): Abrechnungsnummer
* SMC-B-Eintrag für Apotheken: Nicht verwendet
* HBA-Eintrag für Apotheker: Spezifisches Kennzeichen der Apotheker. Kann mehrfach vorkommen (0..100).
* Krankenhäuser (SMC-B-Eintrag): Betriebsstättennummer des Krankenhauses
* Psychotherapeuten (HBA-Eintrag): Spezifisches Kennzeichen der Psychotherapeuten. Kann mehrfach vorkommen (0..100).
* Ärzte (HBA-Eintrag): Spezifisches Kennzeichen der Ärzte. Kann mehrfach vorkommen (0..100).
* Zahnärzte (HBA-Eintrag): Spezifisches Kennzeichen der Zahnärzte. Kann mehrfach vorkommen (0..100).
* Gesetzlichen Krankenkassen (SMC-B-Eintrag): Institutionskennzeichen. Kann mehrfach vorkommen (0..100).

== Namen

=== displayName

Dieses Attribut wird verwendet um vollen Namen einer Institution oder Person in GUI anzuzeigen.

Spezifiziert in https://datatracker.ietf.org/doc/html/rfc2798#section-2.3[RFC2798 Section 2.3]

==== Personen (HBA)

Bei Personen wird `displayName` genutzt, um vollen Namen einer Person gegenüber dem Anwender darzustellen. Es wird empfohlen den Namen wie folgt anzugeben (_Nachname, Vorname_):

----
Dr. Mustermann, Manfred
----

==== Institutionen (SMC-B)

Bei Institutionen wird `displayName` genutzt, um  den Namen einer Institution gegenüber dem Anwender darzustellen.

----
Praxis Dr. Sandra Meyer
----

=== cn
Eindeutiger Name einer Person oder Institution.
LDAP unterstützt grundsätzlich mehrere Namen eines Objekts, in der TI wird jedoch meistens nur ein `cn`-Attribut verwendet, daher ist `cn` in der Regel identisch mit `displayName`.

Spezifiziert in https://datatracker.ietf.org/doc/html/rfc2256#section-5.4[RFC2256 Section 5.4]

=== otherName

NOTE: Dieses Attribut ist deprecated und wird nicht mehr genutzt.

=== organization

Optionaler Name einer Organisation zu welcher diese Eintrag gehört.

Spezifiziert in https://datatracker.ietf.org/doc/html/rfc2256#section-5.11[RFC2256 Section 5.11]

=== givenName

Alle Vornamen einer natürlicher Person. Vornamen sollen nur bei natürlichen Personen befüllt sein, bei Institutionen muss `givenName` leer bleiben.

Spezifiziert in https://datatracker.ietf.org/doc/html/rfc2256#section-5.43[RFC2256 Section 5.43]

=== sn

Nachname eine natürlichen Person. Nachnamen sollen nur bei natürlichen Personen befüllt sein, bei Institutionen muss `sn` leer bleiben.

Spezifiziert in https://datatracker.ietf.org/doc/html/rfc2256#section-5.5[RFC2256 Section 5.5]

=== title
Akademischer oder Adelstitel einer natürlichen Person.

Spezifiziert in https://datatracker.ietf.org/doc/html/rfc2256#section-5.13[RFC2256 Section 5.13]


== Adressdaten

|===
| Beispiel  | Attribute

| Hallesches Ufer 21 +
88451 Dettingen +
Baden-Württemberg +
DE +
| `streetAddress` +
`postalCode` `localityName` +
`stateOrProvinceName` +
`countryCode`
|===

=== streetAddress
Straße und Hausnummer

Spezifiziert in https://datatracker.ietf.org/doc/html/rfc2256#section-5.10[RFC2256 Section 5.10]

Kann als `street` abgekürzt werden

=== postalCode
Postleitzahl
Spezifiziert in https://datatracker.ietf.org/doc/html/rfc2256#section-5.18[RFC2256 Section 5.18]

=== localityName
Ort

Spezifiziert in https://datatracker.ietf.org/doc/html/rfc2256#section-5.8[RFC2256 Section 5.8]

Kann als `l` abgekürzt werden

=== stateOrProvinceName
Bundesland oder Region

Spezifiziert ib https://datatracker.ietf.org/doc/html/rfc2256#section-5.9[RFC2256 Section 5.9]

Kann als `st` abgekürzt werden

==== Gültige Werte für `stateOrProvinceName` in Deutschland:
* Baden-Württemberg
* Bayern
* Berlin
* Brandenburg
* Bremen
* Hamburg
* Hessen
* Mecklenburg-Vorpommern
* Niedersachsen
* Nordrhein-Westfalen
* Rheinland-Pfalz
* Saarland
* Sachsen
* Sachsen-Anhalt
* Schleswig-Holstein
* Thüringen

.Zusätzliche KV-Regionen:
* Nordrhein
* Westfalen-Lippe

=== countryCode [[countryCode]]
Zweistelliger Landeskürzel aus dem Wertebereich https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2[ISO 3166-1 alpha-2]

== Berufliche Informationen

=== professionOID

Berufsgruppe oder Betriebsstätten-Typ innerhalb der Telematikinfrastruktur.

Spezifiziert in https://gemspec.gematik.de/docs/gemSpec/gemSpec_OID/latest/[gemSpec_OID]

Wertebereiche:

* https://gemspec.gematik.de/docs/gemSpec/gemSpec_OID/latest/#3.5.1.1[für Personen (HBA)]
* https://gemspec.gematik.de/docs/gemSpec/gemSpec_OID/latest/#GS-A_4443-12[für Institutionen (SMC-B)]

=== specialization

Der Wertebereich für `specialization` entspricht den in HL7 definierten und für ePA festgelegten Werten.

==== Personen (HBA)

* https://wiki.hl7.de/index.php?title=IG:Value_Sets_für_XDS#DocumentEntry.authorSpecialty[Überblick AuthorSpeciality bei HL7]
* https://github.com/gematik/api-ePA/blob/master/src/vocabulary/value_sets/vs-author-specialty.xml[Normatives ValueSet für ePA]

Bildungsregel: +
`urn:as:{OID Codesystem}:{Code}`

Beispiel für Facharzt Allgemeinmedizin: +
`urn:as:1.2.276.0.76.5.114:010`

==== Institutionen (SMC-B)

* https://wiki.hl7.de/index.php?title=IG:Value_Sets_für_XDS#DocumentEntry.practiceSettingCode[Überblick PracticeSettingCode bei HL7]
* https://github.com/gematik/api-ePA/blob/master/src/vocabulary/value_sets/vs-practice-setting-code.xml[Normatives ValueSet für ePA]

Weitere Ressourcen:

* https://github.com/hl7germany/de.basisprofil.terminology/blob/3917ab759560993f9486562af6811765e357b8fc/input/fsh/codesystems/AerztlicheFachrichtungenIHEXDS.fsh[http://ihe-d.de/CodeSystems/AerztlicheFachrichtungen]
* https://github.com/hl7germany/de.basisprofil.terminology/blob/3917ab759560993f9486562af6811765e357b8fc/input/fsh/codesystems/NichtAerztlicheFachrichtungenIHEXDS.fsh[http://ihe-d.de/CodeSystems/NichtaerztlicheFachrichtungen]

Bildungsregel: +
`urn:psc:{OID Codesystem}:{Code}`

Beispiel für Allgemeinmedizin: +
`urn:psc:1.3.6.1.4.1.19376.3.276.1.5.4:ALLG`

=== entryType
Das Attribut wird automatisch aus `professionOID` berechnet. Werte werden primär durch ePA verwendet.

=== lanr
Bezeichner: LANR
Die lebenslange Arztnummer, kurz LANR, dient der Suche nach Ärzten. Insbesondere für die Suche durch Clients, welche die TelematikID nicht vorliegen haben. +

NOTE: Aktuell enthält die LANR keinen Inhalt.

== Anwendungsdaten

=== mail
Liste aller KIM-Adressen einer Person oder einer Institution. Zur Kompatibilität bleibt die KIM Mail Adresse in diesem Attribut zusätzlich zum Attribut  `komLeData` erhalten.

----
mail: adresse1@anbieter.kim.telematik
mail: adresse2@anbieter.kim.telematik
----

=== komLeData
Enthält die KOM‑LE-Version des Clientmoduls der angegebenen "mail"-Adresse im Attribut "version".
Anhand dieser Version erkennt das sendende Clientmodul, welche KOM‑LE-Version vom Empfänger-Clientmodul unterstützt wird und in welchem Format die Mail an diesen Empfänger versandt wird.

Wenn zu einer KOM‑LE-Mail-Adresse aus Attribut "mail" kein korrespondierender Eintrag im Attribut "komLeData" vorhanden ist, muss automatisch die KOM‑LE-Version `1.0` angenommen werden.

Jeder Datensatz muss vollständig sein und besteht aus:
* der KOM‑LE-Mail-Adresse (Attribut `mail`)
* der zugehörigen KOM‑LE-Version (Attribut `version`)

Zu beachten ist bei der Auswertung bzw. Pflege dieser Daten:

* Ein komLeData‑Eintrag besteht aus:
** der Mail-Adresse (Attribut `mail`)
** der zugehörigen KOM‑LE-Version (Attribut `version`)

* Für jede Mail-Adresse gilt:
** Pro Mail-Adresse darf es genau einen Eintrag in der Datenstruktur `komLeData` geben

* Konsistenzregeln:
** Es dürfen nur Mail-Adressen referenziert werden, die im übergeordneten Attribut `mail` enthalten sind
** Wenn zu einer Mail-Adresse kein Eintrag existiert,
*** muss KOM‑LE-Version `1.0` angenommen werden

* Wird eine Mail-Adresse gelöscht:
** muss auch der zugehörige komLeData‑Eintrag gelöscht werden

* Beim Schreiben der Daten:
** wird immer die gesamte Liste geschrieben

* Für Änderungen gilt:
** zuerst den aktuellen Eintrag lesen
** anschließend die Änderungen in der Liste vornehmen
** danach die komplette Liste wieder zurückschreiben

.Beispiel für den Wert eines komLeData-Eintrags in der flachen Liste (Ausgabe einer LDAP-Suche):
----
komLeData: 1.0,mc_smcb_za@dom1.komle.telematik-test
komLeData: 1.0,mz_smcb_za@dom2.kim.telematik-test
komLeData: 1.0,mz_smcb_za@dom1.kim.telematik-test
komLeData: 1.0,mb_secu_sm@dom3.kim.telematik-test
komLeData: 1.0,mb_secu_sm@dom4.kim.telematik-test
komLeData: 1.5,ak_secu_102@dom5.kim.telematik-test
----

=== kimData
Enthält die KOM‑LE-Version des Clientmoduls der angegebenen "mail"-Adresse im Attribut "version".
Zusätzlich kann zur KOM‑LE-Version ein `+` angegeben sein.

Anhand dieser Version erkennt das sendende Clientmodul:
* welche KOM‑LE-Version vom Empfänger-Clientmodul unterstützt wird
* in welchem Format die Mail an diesen Empfänger versandt wird

Wenn ein zusätzliches `+` angegeben ist:
* können mit dieser "mail"-Adresse Nachrichten größer 15 MiB verarbeitet werden

Wenn noch keine Version zu einer KOM‑LE-Mail-Adresse angegeben wurde:
* wird vom VZD automatisch die Version `1.0` eingetragen

Jeder Datensatz muss vollständig sein und enthält:
* die KOM‑LE-Mail-Adresse (Attribut `mail`)
* die KOM‑LE-Version (Attribut `version`)

Zusätzlich kann ein Datensatz enthalten:
* ein oder mehrere Anwendungskennzeichen (Attribut `appTags`)

Dabei gilt:
* Das Attribut `appTags` ist optional
* Wenn kein Anwendungskennzeichen vorhanden ist,
** können alle KIM-Anwendungen an diesen Empfänger versendet werden

Die Kodierung eines Eintrags erfolgt wie folgt:
* Bestandteile werden durch `,` getrennt
** Mail-Adresse
** KOM‑LE-Version
** optional: Anwendungskennzeichen

* Mehrere Anwendungskennzeichen werden durch `|` getrennt

Zu beachten ist bei der Auswertung bzw. Pflege dieser Daten:

* Ein kimData‑Eintrag besteht aus:
** der Mail-Adresse (Attribut `mail`)
** der zugehörigen KOM‑LE-Version (Attribut `version`)
** optional einem `+` hinter der Version
** optional einem oder mehreren Anwendungskennzeichen (Attribut `appTags`)

* Wenn mehrere Anwendungskennzeichen angegeben sind:
** werden sie im LDAP-Attribut durch das Zeichen `|` getrennt

* Für jede Mail-Adresse gilt:
** Es darf nur einen kimData‑Eintrag geben

* Wird eine Mail-Adresse gelöscht:
** muss auch der zugehörige kimData‑Eintrag gelöscht werden

* Beim Schreiben der Daten:
** wird immer der gesamte kimData‑Eintrag geschrieben
** inklusive aller enthaltenen Attribute und Werte (für alle Mail-Adressen)

* Für Änderungen gilt:
** zuerst den aktuellen Eintrag lesen
** anschließend Änderungen vornehmen
** danach den kompletten Eintrag wieder zurückschreiben

.Beispiel für den Wert eines kimData-Eintrags in der flachen Liste (Ausgabe einer LDAP-Suche):
----
kimData: mc_smcb_za@dom1.komle.telematik-test,1.0,eEB
kimData: mz_smcb_za@dom2.kim.telematik-test,1.0,DALE-UV|eEB
kimData: mz_smcb_za@dom1.kim.telematik-test,1.0
kimData: mb_secu_sm@dom3.kim.telematik-test,1.0
kimData: mb_secu_sm@dom4.kim.telematik-test,1.0
kimData: ak_secu_102@dom5.kim.telematik-test,1.5
----

NOTE: Aktuell werden keine appTags bzw. Anwendungskennzeichen verwendet.

=== maxKOMLEadr
Maximale Anzahl von mail Adressen in den KOM-LE-Fachdaten. 
Falls kein Wert eingetragen wurde, können beliebig viele mail Adressen in den KOM-LE Fachdaten eingetragen werden.
Falls ein Wert eingetragen wurde, können maximal so viele mail Adressen in den KOM-LE Fachdaten eingetragen werden. 

== Zertifikate

=== userCertificate
X509-Zertifikate werden für Verschlüsselung der KIM-Nachrichten sowie bei der Berechtigungserteilung in der ePA verwendet.

Zertifikate werden als DER-kodierte Binary transportiert.

=== notBefore
Wird vom VZD bei Eintrag eines Zertifikats aus dem Zertifikat entnommen und ist nicht änderbar.
Wird vom VZD zur Ermittlung der zeitlich gültigen Zertifikate genutzt.
Dieses Attribut ist nicht in der flachen Liste enthalten.

=== userCertificate.active
Wird vom VZD eingetragen.
Wert == TRUE, wenn das userCertificate gemäß OCSP gültig ist (OCSP Response Status "good"), Wert == FALSE bei Zertifikaten von noch nicht freigeschalteten Karten (OCSP Response Status "unknown").
Wenn das Attribut den Wert FALSE enthält, wird der Zertifikatseintrag nicht in die flache Liste übernommen.

=== notAfter
Wird vom VZD bei Eintrag eines Zertifikats aus dem Zertifikat entnommen und ist nicht änderbar.
Wird vom VZD zur Ermittlung der zeitlich gültigen Zertifikate genutzt.
Dieses Attribut ist nicht in der flachen Liste enthalten.

=== serialNumber
Wird vom VZD bei Eintrag eines Zertifikats aus dem Zertifikat entnommen und ist nicht änderbar.
Kann zur Suche nach Zertifikaten genutzt werden.
Dieses Attribut ist nicht in der flachen Liste enthalten.

=== issuer
Wird vom VZD bei Eintrag eines Zertifikats aus dem Zertifikat entnommen und ist nicht änderbar.
Kann zur Suche nach Zertifikaten genutzt werden.
Dieses Attribut ist nicht in der flachen Liste enthalten.

=== publicKeyAlgorithm
Nutzt das Zertifikat RSA oder ECC?
Wird vom VZD bei Eintrag eines Zertifikats aus dem Zertifikat entnommen und ist nicht änderbar.
Kann zur Suche nach Zertifikaten genutzt werden.
Dieses Attribut ist nicht in der flachen Liste enthalten.

== Systemdaten

=== holder
Enthält eine Liste von Organisationen, die für die Administration dieses Datensatzes berechtigt sind.

=== dataFromAuthority
Enthält `TRUE` wenn die Daten durch einen Kartenherausgeber eingestellt wurden.

=== personalEntry
Enthält `TRUE` wenn Eintrag eine natürliche Person beschreibt (einen Leistungsebringer) - d.h. einen HBA Empfänger. Enthält `FALSE` wenn es um einen Eintrag einer Institution handelt, d.h. SMC-B Empfänger. 

=== changeDateTime
Zeitstempel der letzten Änderung. Wert wird bei jeder Aktualisierung durch VZD auf aktuelle Systemzeit gesetzt.

=== active
Mit diesem Attribut im Basiseintrag (Verzeichnisdienst_Eintrag in Abb_VZD_logisches_Datenmodell) kann der Client (Kartenherausgeber, TSP) die Aufnahme des VZD-Eintrags in die flache Liste steuern. Wenn das Attribut beim Anlegen eines VZD-Eintrags mit Zertifikat nicht angegeben wird, setzt der VZD das Attribut active auf TRUE (Default-Wert).
Bei FALSE wird der Eintrag vom VZD aus der flachen Liste entfernt bzw. nicht übertragen.
Dieses Attribut ist nicht in der flachen Liste enthalten.
Wenn der VZD beim zeitlichen Ablauf des letzten Zertifikats einen VZD-Eintrag aus der flachen Liste entfernt, bleibt das Attribut active unverändert. Beim erneuten Hinzufügen eines Zertifikats wird der VZD-Eintrag also wieder in die flache Liste übernommen, wenn dieses Attribut den Wert "true" enthält.

=== meta
Kann von den pflegenden Clients zur Abstimmung der Prozesse zwischen z. B. Kartenherausgeber und TSP genutzt werden. Dieses Attribut wird durch den VZD nicht ausgewertet. Die Werte für dieses Attribut müssen von den pflegenden Organisationen festgelegt und abgestimmt werden.
Array von Strings (wird in LDAP auf <String, String> gemappt).
Dieses Attribut ist nicht in der flachen Liste enthalten.
Kann mehrfach vorkommen (0..100).

== Beispiele

=== Darstellung von Personen und Institutionen in einer Liste

|===
^| Typ | Name | Nachname | Vorname | Adresse | PLZ | Ort

^| 🏥
| Praxis Helga Freifrau Mondwürfel
|
|
| Bahnhof Str. 13
| 91234
| Nürnberg

^| 👩‍⚕️
| Oldenburg, Petra
| Oldenburg
| Petra
| Hallesches Ufer 21
| 88451
| Dettingen

^| `personalEntry`
| `displayName`
| `sn`
| `givenName`
| `street`
| `postalCode`
| `localityName`
|===


== Wer kann Attribute im LDAP VZD befüllen und ändern


:table-caption!:
[options="header"]
[cols="2s,^1,^1,^1,^1"]
|===
|LDAP-Directory Attribut|       | Zertifikat    | Client    | KIM Anbieter
|givenName              | HBA   |  x            |           |
|                       | SMC-B 3+| nicht verwendet
|sn                     | HBA   |  x            |           |
|                       | SMC-B 3+| Vom VZD als Kopie des Attributs displayName eingetragen
|cn                     | HBA   3+| Vom VZD als Kopie des Attributs displayName eingetragen
|                       | SMC-B 3+| Vom VZD als Kopie des Attributs displayName eingetragen
|displayName            | HBA   |               |  x     |
|                       | SMC-B |               |  x     |
|streetAddress          | HBA   |               |  x     |
|                       | SMC-B |               |  x     |
|postalCode             | HBA   |               |  x     |
|                       | SMC-B |               |  x     |
|countryCode            | HBA   |               |  x     |
|                       | SMC-B |               |  x     |
|localityName           | HBA   |               |  x     |
|                       | SMC-B |               |  x     |
|stateOrProvinceName    | HBA   |               |  x     |
|                       | SMC-B |               |  x     |
|title                  | HBA   |               |  x     |
|                       | SMC-B 3+| nicht verwendet
|organization           | HBA   |               |  x     |
|                       | SMC-B |               |  x     |
|otherName              | HBA   |               |  x     |
|                       | SMC-B |               |  x     |
|specialization         | HBA   |               |  x     |
|                       | SMC-B |               |  x     |
|domainID               | HBA   |               |  x     |
|                       | SMC-B |               |  x     |
|holder                 | HBA   |               |  x     |
|                       | SMC-B |               |  x     |
|maxKOMLEadr            | HBA   |               |  x     |
|                       | SMC-B |               |  x     |
|personalEntry          | HBA   |  x            |        |
|                       | SMC-B |  x            |        |
|dataFromAuthority      | HBA   3+| wird vom VZD eingetragen
|                       | SMC-B 3+| wird vom VZD eingetragen
|userCertificate        | HBA   |               |  x     |
|                       | SMC-B |               |  x     |
|entryType              | HBA   | x             |        |
|                       | SMC-B | x             |        |
|telematikID            | HBA   | x             |  x     |
|                       | SMC-B | x             |  x     |
|professionOID          | HBA   | x             |        |
|                       | SMC-B | x             |        |
|usage                  | HBA   |               |  x     |
|                       | SMC-B |               |  x     |
|description            | HBA   |               |  x     |
|                       | SMC-B |               |  x     |
|mail                   | HBA   |               |        |  x
|                       | SMC-B |               |        |  x
|komLeData              | HBA   |               |        |  x
|                       | SMC-B |               |        |  x
|kimData                | HBA   |               |        |  x
|                       | SMC-B |               |        |  x
|changeDateTime         | HBA   3+| wird vom VZD eingetragen
|                       | SMC-B 3+| wird vom VZD eingetragen
|===

*Erläuterungen zu den Spalten*:

* Zertifikat
- Der Wert für das LDAP Attribut wird dem Zertifikat entnommen.
- Bei Hinzufügen eines Zertifikats wird das LDAP Attribut aktualisiert.

* Client
- Der Wert für das LDAP Attribut wird durch den Client des Kartenherausgebers gepflegt.

* KIM Anbieter
- Der Wert für das LDAP Attribut wird durch den KIM-Abieter gepflegt.

*Erläuterungen für spezielle Attribute*:

* *personalEntry*: Beim Löschen von Zertifikaten wird der Wert neu berechnet. Wenn alle Zertifikate gelöscht wurden, wird der Wert auf "FALSE" gesetzt.

* *Aus den Zertifikaten befüllte Attribute* *entryType*, *professionOID*: Beim Löschen eines Zertifikats wird der Wert auf Basis aller verbleibender Zertifikate neu berechnet und gesetzt.

* *Alle aus den Zertifikaten befüllte Attribute (givenName, sn, personalEntry, telematikID, professionOID, entryType)* werden beim Hinzufügen eines neuen Zertifikats aktualisiert bzw. ergänzt.

* *telematikID* im VZD Basiseintrag: Wird aus dem Zertifikat befüllt. Kann in dem REST Interface zwar angegeben, aber nicht auf einen anderen Wert geändert werden.

|===
