= 🔍 Suche im Verzeichnisdienst
gematik, Systems Engineering

== Allgemeines

Die Seite gibt Hinweise zur Suche im VZD für Anwendungen. Die Suche von Einträgen für den Anwendungen/Endanwender ist über Schnittstelle `I_Directory_Query` mit LDAPv3 möglich. Gesucht werden kann nach allen link:LDAP_Attribute.adoc[Attributen].

== Eine Auswahl von Suchkriterien

=== Suche nach Art der Organisation/Leistungserbringers und Spezialisierung*

Dafür kann man unter anderem folgende Attribute in der Suchanfrage verwenden:

* `professionOID` 
** Profession OID - Siehe [gemSpec_VZD#Tab_VZD_Mapping_Eintragstyp_und_ProfessionOID].

* `specialization` 
** Fachgebiet entsprechend https://wiki.hl7.de/index.php?title=IG:Value_Sets_f%C3%BCr_XDS#DocumentEntry.practiceSettingCode[FHIR HL7]

.Beispiel für die Suche nach einer Arztpraxis für Allgemeinmedizin
[cols="h,a"] 
|===
|LDAP Filter       
m|(&(professionOID=1.2.276.0.76.4.50)(specialization=urn:psc:1.3.6.1.4.1.19376.3.276.1.5.4:ALLG))
|===

=== Suche nach Adresse bzw. in einem Suchgebiet

Dafür kann man unter anderem folgende Attribute in der Suchanfrage verwenden:

* `stateOrProvinceName`
** Bundesland - z.B. "Berlin"
  
* `postalCode` 
** Postleitzahl - z.B. "10117"

* `localityName` 
** Ort - z.B. "Berlin"

* `streetAddress` 
** Straße - z.B. "Friedrichstraße"

.Beispiel für die Suche nach einer Adresse
[cols="h,a"] 
|===
|LDAP Filter
m|(&(stateOrProvinceName=Berlin)(postalCode=10117)(localityName=Berlin)(streetAddress=Friedrichstraße*))
|===
{nbsp} +

=== Suche bei bekanntem Namen

Dafür kann man unter anderem folgende Attribute in der Suchanfrage verwenden:

* `displayName` 
** Name der Organisation oder der Person - z.B. "Meier"
** Für die Attribute kann ebenfalls die Suche mit Wildcards entsprechend LDAP genutzt werden z.B. "Meier*".

.Beispiel für die Suche nach Namen
[cols="h,a"] 
|===
|LDAP Filter       
m|(displayName=Meier*)
|===

=== Kombination der Suchkriterien

[cols="h,a"] 
|===
|LDAP Filter
m|(&(professionOID=1.2.276.0.76.4.50)(specialization=urn:psc:1.3.6.1.4.1.19376.3.276.1.5.4:ALLG)(stateOrProvinceName=Berlin)(postalCode=10117)(localityName=Berlin)(streetAddress=Friedrichstraße*)(displayName=Meier*))
|===


