ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

:imagesdir: ../images
:toc: macro
:toclevels: 5
:toc-title: Table of Contents
:numbered:

image:gematik_logo.svg[width=70%]

toc::[]

= Änderuntgen an Spezifikation gemSpec_VZD_FHIR_Directory
Dieses Dokument informiert über die Änderungen an Spezifikation gemSpec_VZD_FHIR_Directory, welche noch nicht auf dem gematik Fachportal veröffentlicht wurden.
Vor der Veröffentlichung auf dem Fachportal erfolgen noch Reviews. Folge dieser Reviews können Änderungen bis zur finalen Veröffentlichung bedingen.

== Anwendungsfälle
=== Eigentümer ändert seinen Eintrag im FHIR-Directory (gemSpec_VZD_FHIR_Directory#5.2)
*AF_10037 Einträge im VZD-FHIR-Directory ändern*

.AF_10037 Einträge im VZD-FHIR-Directory ändern 
|===
|Attribute |Bemerkung

|Beschreibung
|Organisationen können ihren Eintrag im VZD-FHIR-Directory an die eigenen Strukturen anpassen. 
Leistungserbringer können z. B. die TI-Messenger-Adresse in ihrem Eintrag hinzufügen. 
Der Basiseintrag einer Organisation oder eines Leistungserbringers wird wie bisher durch die Kartenherausgeber erstellt. 
Die Organisation KANN eigene mit dem Basiseintrag verlinkte FHIR-Ressourcen erstellen, um die Struktur der Organisation abzubilden. 
Zum Beispiel können Krankenhäuser ihre Fachabteilungen als HealthcareService-Einträge abbilden, die mit dem Organization-Eintrag verlinkt sind. 
Wenn der Org-Admin oder LE kein gültiges owner-accesstoken vom VZD-FHIR-Directory im Client vorliegt, 
muss die Authentisierung mittels OIDC an einem IDP der TI-IDP-Föderation erfolgen. 
Nach erfolgreicher Authentisierung ist die durch den IDP bestätigte Telematik-ID des Leistungserbringers oder der Organisation am Auth-Service bekannt. 
Für den Aufruf der FHIR-Operationen durch den Client stellt der Auth-Service dem Client ein owner-accesstoken aus, 
dass auch die Telematik-ID des LE oder der Organisation enthält.

|Vorbedingung
|Die Organisation oder der Leistungserbringer hat bereits einen Basiseintrag im VZD-FHIR-Directory. Eine Authenticator-App des IDP steht zur Verfügung, 
mit der die Organisations-Identität oder die Leistungserbringer-Identität bei einem IDP der TI-IDP-Föderation bestätigt werden kann. 

|Fehlermeldungen
|


|===

++++
<p align="left">
  <img width="75%" src=../images/diagrams/SequenceDiagram.FHIR-Directory.owner.png>
</p>
++++

Neue Beschreibung für Anwendungsfall AF_10037: +
 +
Der Auth-Service des VZD-FHIR-Directory muss übergebene Token entsprechend Akzeptanzkriterium ML-xxxxxx prüfen und bei erfolgreicher Prüfung ein owner-accesstoken ausstellen und zurückgeben. +
Wird der Auth-Service des VZD-FHIR-Directory ohne Token aufgerufen, muss er die Authentifizierung entsprechend OpenID Connect unterstützen. +
Der Auth-Service soll die Authentifizierung entsprechend OpenID Connect auch für Zugriffe durch Org-Admins (SMC-B/Organization) - zusätzlich zur Authentifizierung mit RegService-OpenID-Token - unterstützen. +
 +
 +
*Akzeptanzkriterien für den Anwendungsfall "AF_10037 OrganizationDirectory-Einträge im VZD-FHIR-Directory ändern"* +
 +
*ML-123873 - Authentifizierung am Endpunkt /owner (VZD-FHIR-Directory, Sicherheitsgutachten)* +
Am Endpunkt /owner des FHIR-Proxy darf die Authentifizierung nur für Nutzer erfolgreich sein, die ein gültiges Accesstoken vom VZD-FHIR-Directory vorweisen. +
 +
*ML-123874 - Nur Einträge mit eigener Telematik-ID verändern (VZD-FHIR-Directory)* +
Im bei der Authentifizierung verwendeten Accesstoken ist die Telematik-ID des Nutzers enthalten. 
Nur der Eintrag (PractitionerDirectory oder OrganizationDirectory) mit der eigenen Telematik-ID darf verändert werden. 
Dabei dürfen nur die Attribute verändert werden, die nicht vom VZD-LDAP-Directory synchronisiert werden. +
 +
 
IMPORTANT: Folgendes Akzeptanzkriterium wird gestrichen (nur HealthcareServices können mit dem eigenen Organization Eintrag verlinkt werden): +
*ML-123482 - Selbst angelegte OrganizationDirectory-Einträge MÜSSEN mit dem eigenen Basiseintrag verlinkt sein (VZD-FHIR-Directory)* +
 +

Neue Akzeptanzkriterien: +
 +
*ML-xxxxxx - Token Prüfung (VZD-FHIR-Directory)* +
Die Accesstoken müssen vom VZD-FHIR-Directory für den Endpunkt /owner geprüft werden: +

- Laden des Zertifikats
- Prüfung Audience aus dem Token (muss der /owner Schnittstelle entsprechen)
- Prüfung ProfessionOID aus dem Token (*was wird geprüft?*) 
- Prüfung Signatur des Tokens gemäß RFC7515.

Zur Prüfung der Signatur ist das X.509-Root-CA Zertifikat der TI erforderlich. 
Das X.509-Root-CA Zertifikat MUSS im Truststore des VZD-FHIR-Directory gespeichert sein.

Das VZD-FHIR-Directory MUSS wöchentlich prüfen, ob neue X.509-Root-CA-Versionen existieren und Cross-Zertifikate verfügbar sind. 
Falls dies der Fall ist, so MUSS das VZD-FHIR-Directory diese neue Root-Versionen in seinen Truststore importieren. +
 +
Nach der Erzeugung einer neuen Root-Version der X.509-Root-CA der TI werden dessen selbstsigniertes Zertifikat und Cross-Zertifikate 
auf den Download-Punkt gemäß [ROOT-CA] abgelegt. Automatisiert kann das VZD-FHIR-Directory von dort die Verfügbarkeit neuer Versionen überwachen. 
Zusätzlich kann der folgende Download-Punkt unter [ROOT-CA-JSON] verwendet werden. 
Dort werden die aktuellen Root-Zertifikate inkl. deren Cross-Zertifikate gepflegt. 
Im Regelfall wird alle zwei Jahre eine neue Root-Version erzeugt. Die Dateigröße der heruntergeladenen JSON-Datei kann man als Hashfunktion verwenden. 
Hiermit kann man beispielsweise mit Hilfe des Tools curl die HTTP-Methode HEAD verwenden und damit erfahren ob die lokale Kopie der JSON-Datei noch aktuell ist. 
Die JSON-Datei ist ein Array, in dem Associative Arrays als Elemente aufgeführt werden. 
Diese Elemente enthalten je ein Root-Zertifikat inkl. Cross-Zertifikate für das chronologisch vorhergehende und das nachfolgende Root-Zertifikat. 
D. h.,  kryptographisch gesehen stellt dies eine doppelt verkettet Liste dar. 
Die Element im Array sind in chronologischer Ordnung sortiert. Im Folgenden wird ein Beispiel dargestellt. +

