@startuml
top to bottom direction
skinparam linetype ortho
skinparam packageStyle rectangle
skinparam wrapWidth 180
skinparam nodesep 8
skinparam ranksep 25
hide empty members

package "Krankenhaus" {

class Organization_Krankenhaus {
#<color:#0000FF>identifier: telematikID, IKNR</color>
#<color:#0000FF>name : Name der Organization</color>
-alias :
#<color:#0000FF>type : 1.2.276.0.76.4.53 Krankenhaus</color>
#<color:#0000FF>active : true</color>
}

class HealthcareService_Krankenhaus {
#<color:#0000FF>type : GESU - Öffentliches Gesundheitswesen</color>
#<color:#0000FF>Origin: ldap</color>
-speciality : -
-name : -
#availableTime: Öffnungszeiten
}

class Location_Krankenhaus {
#name : -
#<color:#0000FF>type : VZD</color>
#<color:#0000FF>address : Adresse</color>
-position : VZD GeoKoordinaten
}

class Endpoint_Krankenhaus {
#<color:#0000FF>name: Name</color>
#<color:#0000FF>endpointVisibility : -</color>
#<color:#0000FF>status : active</color>
#<color:#0000FF>connectionType : EndpointConnectionType</color>
#<color:#0000FF>payloadType : EndpointPlayloadType</color>
#<color:#0000FF>address : KIM/TIM Adresse</color>
}

Organization_Krankenhaus <-- HealthcareService_Krankenhaus : providedBy
HealthcareService_Krankenhaus --> Location_Krankenhaus : location
HealthcareService_Krankenhaus --> Endpoint_Krankenhaus : endpoint
}

package "Standort" {

class HealthcareService_Standort {
+name: <color:#2bcc0e>Standortname</color>; Zentrenname; Einrichtungsname; Fachabteilungsname
+<color:#2bcc0e>active : "Aktiv"</color>
+<color:#2bcc0e>identifier.standortId: 123456</color>
+<color:#2bcc0e>category[vzdLevel]: "Standort"</color>
+<color:#2bcc0e>name : Name der Organization - Standort 123</color>
-alias : -
-type : -
+<color:#2bcc0e>GültigVon : 2018-01-01</color>
+<color:#2bcc0e>GültigBis : -</color>
+<color:#2bcc0e>LetzteÄnderung : 2025-12-19</color>
+<color:#2bcc0e>extension[version] : Version</color>
+<color:#2bcc0e>extension[ausnahme] : Ausnahme</color>
-speciality : -
-telecom : -
-availableTime: -
}

class Location_Standort {
-name : -
+<color:#2bcc0e>type : StandortVZ</color>
+<color:#2bcc0e>address : Adresse</color>
+<color:#2bcc0e>address.state : Bundesland</color>
+<color:#2bcc0e>address.extension[ags] : Gemeindeschlüssel</color>
+<color:#2bcc0e>address.extension[adresstyp] : Adresstyp</color>
+<color:#2bcc0e>extension[kvBezirk] : KVBezirk</color>
+<color:#2bcc0e>extension[postadresse] : PostAdresse</color>
+<color:#2bcc0e>position : GeoKoordinaten</color>
}

Organization_Krankenhaus <-- HealthcareService_Standort : providedBy
HealthcareService_Standort --> Location_Standort : location
}

package "Zentren" {

class HealthcareService_Zentren {
+name: <color:#2bcc0e>Standortname; Zentrenname</color>; Einrichtungsname; Fachabteilungsname
+<color:#2bcc0e>identifier : erId aus Standortdaten</color>
-name : -
-alias : -
+<color:#2bcc0e>type : ZentrenArt aus Standortdaten</color>
-active : -
-speciality : -
-telecom : -
-availableTime: -
}

Organization_Krankenhaus <-- HealthcareService_Zentren : providedBy
HealthcareService_Zentren -up-> HealthcareService_Standort : extension[offeredIn]
}

package "Einrichtung" {

class HealthcareService_Einrichtung {
+name: <color:#2bcc0e>Standortname</color>; Zentrenname; <color:#2bcc0e>Einrichtungsname</color>; Fachabteilungsname
+<color:#2bcc0e>identifier:BSNR : 999999999</color>
+<color:#2bcc0e>identifier:standortnummer : Standortnummer</color>
+<color:#2bcc0e>identifier:abrechnungsIK : AbrechnungsIK</color>
+<color:#2bcc0e>category[vzdLevel]: "Einrichtung"</color>
+<color:#2bcc0e>name : Name der Organization - Name der Einrichtung</color>
-alias : -
+<color:#2bcc0e>type : Einrichtungstyp</color>
+<color:#2bcc0e>active : "Aktiv"</color>
+<color:#2bcc0e>extension[ausnahme] : Ausnahme</color>
+<color:#2bcc0e>extension[versorgungsmerkmale] : PSY, DRG</color>
+<color:#2bcc0e>extension[traeger] : Träger/Trägerart/Rechtsform/Sitz/Register</color>
-speciality : -
-telecom : -
-availableTime: -
}

class Location_Einrichtung {
-name : -
+<color:#2bcc0e>type : EinrichtungVZ</color>
+<color:#2bcc0e>address : Adresse</color>
+<color:#2bcc0e>position : GeoKoordinaten</color>
}

Organization_Krankenhaus <-- HealthcareService_Einrichtung : providedBy
HealthcareService_Einrichtung --> Location_Einrichtung : location
HealthcareService_Einrichtung -up-> HealthcareService_Standort : extension[offeredIn]
}

package "Fachabteilung" {

class HealthcareService_Fachabteilung {
+name: <color:#2bcc0e>Standortname</color>; Zentrenname; <color:#2bcc0e>Einrichtungsname; Fachabteilungsname</color>
+<color:#2bcc0e>identifier: erId aus Standortdaten</color>
+<color:#2bcc0e>category[vzdLevel]: "Fachabteilung"</color>
+<color:#2bcc0e>name : Name der Organization - Name der Einrichtung - Name der Fachabteilung</color>
-alias : -
+<color:#2bcc0e>type : Fachabteilungsschlüssel</color>
+<color:#2bcc0e>active : "Aktiv"</color>
-speciality : -
-telecom : -
-availableTime: -
}

Organization_Krankenhaus <-- HealthcareService_Fachabteilung : providedBy
HealthcareService_Fachabteilung -up-> HealthcareService_Einrichtung : extension[offeredIn]
}

@enduml
