name: Publish AsciiDoc

on:
  push:
    branches:
      - develop

permissions:
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Asciidoctor
        run: sudo apt-get update && sudo apt-get install -y asciidoctor

      - name: Generate HTML
        run: |
          mkdir public
          asciidoctor \
            docs/FHIR_VZD_Search_Best_Practices.adoc \
            -o public/index.html

      - uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages

    steps:
      - uses: actions/deploy-pages@v4
