openapi: 3.0.3
info:
  title: I_VZD_Holder_Authenticate_Service
  description: REST interface to authenticate Holder.
  version: 1.0.0
  # initiale Version

externalDocs:
  description: I_VZD_Holder_Authenticate_Service REST interface
  url: https://www.gematik.de
servers:
  - url: "{protocol}://{hostname}"
    variables:
      protocol:
        default: http
      hostname:
        default: "localhost:8085"

paths:
  /holder-authenticate:
    get:
      summary: "Endpunkt zur Holder-Authentifizierung"
      description: "Endpunkt f端r die Authentisierung von Holder am FHIR-Proxy."
      operationId: getHolderAuthenticate
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HolderAccessToken'
        401:
          description: Unauthorized
          #  The WWW-Authenticate header in the response is OAuth.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        503:
          description: Service unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    HolderAccessToken:
      properties:
        access_token:
          type: string
          description: Json-WebToken as BP256R1
        client_id:
          type: string
          description: id of Keycloak client
        token_type:
          type: string
          enum:
            - bearer
        expires_in:
          type: integer
          format: int64
    Error:
      type: object
      properties:
        message:
          type: string
          description: (optionale) Fehlernachricht
        errors:
          maxItems: 50
          minItems: 0
          type: array
          items:
            $ref: '#/components/schemas/InnerError'
    InnerError:
      type: object
      properties:
        attributeName:
          description: Name des Attributs, in dem ein Fehler erkannt wurde
          type: string
        attributeError:
          description: Beschreibung des erkannten Fehlers
          type: string
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: "https://auth-test.vzd.ti-dienste.de:9443/auth/realms/RSDirectoryAdministration/protocol/openid-connect/token"
          scopes:
            VZD:DirectoryAdministration:
              Erlaubt Umtausch des Oauth2-Access-Tokens zu einem Access-Token f端r die I_VZD_Person_Institution_linking-Schnittstellen
              端ber deb hier beschriebenen /holder-authenticate Endpunkt.
            VZD:DirectoryRead:
              Marker-Scope f端r Nur-Lese-Zugriff.
security:
  - OAuth2:
      - "VZD:DirectoryAdministration"
